export interface RoadmapTopic {
  name: string;
  total: number;
}

export interface Roadmap {
  id: string;
  name: string;
  icon: string; // emoji
  color: string; // hex color
  description: string;
  topics: RoadmapTopic[];
}

export interface RoadmapCategory {
  id: string;
  name: string;
  icon: string; // emoji
  roadmaps: Roadmap[];
}

export const ROADMAP_CATEGORIES: RoadmapCategory[] = [
  // ─────────────────────────────────────────────
  // 1. Computer Science & Programming
  // ─────────────────────────────────────────────
  {
    id: 'cs',
    name: 'Computer Science & Programming',
    icon: '💻',
    roadmaps: [
      {
        id: 'dsa',
        name: 'Data Structures & Algorithms',
        icon: '🧮',
        color: '#6C5CE7',
        description: 'Master DSA for coding interviews & CP',
        topics: [
          { name: 'Learn the Basics', total: 54 },
          { name: 'Sorting Techniques', total: 7 },
          { name: 'Arrays', total: 40 },
          { name: 'Binary Search', total: 32 },
          { name: 'Strings', total: 15 },
          { name: 'Linked Lists', total: 31 },
          { name: 'Recursion', total: 25 },
          { name: 'Bit Manipulation', total: 18 },
          { name: 'Stacks & Queues', total: 30 },
          { name: 'Sliding Window & Two Pointers', total: 12 },
          { name: 'Heaps', total: 17 },
          { name: 'Greedy', total: 15 },
          { name: 'Binary Trees', total: 38 },
          { name: 'BST', total: 16 },
          { name: 'Graphs', total: 53 },
          { name: 'Dynamic Programming', total: 55 },
          { name: 'Tries', total: 7 },
        ],
      },
      {
        id: 'python',
        name: 'Python Programming',
        icon: '🐍',
        color: '#00B894',
        description: 'Learn Python from basics to advanced',
        topics: [
          { name: 'Basics & Syntax', total: 12 },
          { name: 'Data Types', total: 8 },
          { name: 'Control Flow', total: 10 },
          { name: 'Functions', total: 9 },
          { name: 'OOP', total: 15 },
          { name: 'File Handling', total: 7 },
          { name: 'Error Handling', total: 6 },
          { name: 'Modules & Packages', total: 8 },
          { name: 'Comprehensions & Generators', total: 7 },
          { name: 'Decorators & Metaclasses', total: 5 },
          { name: 'Concurrency', total: 6 },
          { name: 'Testing', total: 5 },
        ],
      },
      {
        id: 'java',
        name: 'Java Programming',
        icon: '☕',
        color: '#E17055',
        description: 'Complete Java development roadmap',
        topics: [
          { name: 'Basics & Syntax', total: 10 },
          { name: 'OOP', total: 14 },
          { name: 'Collections Framework', total: 12 },
          { name: 'Exception Handling', total: 6 },
          { name: 'Multithreading', total: 10 },
          { name: 'File I/O', total: 6 },
          { name: 'Generics', total: 5 },
          { name: 'Lambda & Streams', total: 8 },
          { name: 'JDBC', total: 5 },
          { name: 'Design Patterns', total: 12 },
        ],
      },
      {
        id: 'c-cpp',
        name: 'C/C++ Programming',
        icon: '⚙️',
        color: '#0984E3',
        description: 'Systems programming with C and C++',
        topics: [
          { name: 'C Basics', total: 10 },
          { name: 'Pointers & Memory', total: 12 },
          { name: 'Structs & Unions', total: 6 },
          { name: 'C++ OOP', total: 14 },
          { name: 'STL', total: 15 },
          { name: 'Templates', total: 6 },
          { name: 'Smart Pointers', total: 5 },
          { name: 'Concurrency', total: 7 },
        ],
      },
      {
        id: 'javascript',
        name: 'JavaScript Programming',
        icon: '⚡',
        color: '#FDCB6E',
        description: 'Modern JavaScript from ES6 to beyond',
        topics: [
          { name: 'Basics & ES6+', total: 12 },
          { name: 'DOM Manipulation', total: 8 },
          { name: 'Async Programming', total: 10 },
          { name: 'Closures & Scope', total: 6 },
          { name: 'Prototypes & Classes', total: 7 },
          { name: 'Error Handling', total: 5 },
          { name: 'Modules', total: 5 },
          { name: 'Event Loop', total: 4 },
          { name: 'Web APIs', total: 8 },
        ],
      },
      {
        id: 'go',
        name: 'Go Programming',
        icon: '🐹',
        color: '#00CEC9',
        description: 'Build fast, concurrent apps with Go',
        topics: [
          { name: 'Basics & Types', total: 8 },
          { name: 'Functions & Methods', total: 6 },
          { name: 'Structs & Interfaces', total: 8 },
          { name: 'Goroutines & Channels', total: 10 },
          { name: 'Error Handling', total: 5 },
          { name: 'Packages', total: 5 },
          { name: 'Testing', total: 4 },
          { name: 'Concurrency Patterns', total: 7 },
        ],
      },
      {
        id: 'rust',
        name: 'Rust Programming',
        icon: '🦀',
        color: '#E84393',
        description: 'Safe systems programming with Rust',
        topics: [
          { name: 'Ownership & Borrowing', total: 10 },
          { name: 'Structs & Enums', total: 7 },
          { name: 'Pattern Matching', total: 5 },
          { name: 'Traits', total: 8 },
          { name: 'Lifetimes', total: 6 },
          { name: 'Error Handling', total: 5 },
          { name: 'Concurrency', total: 7 },
          { name: 'Macros', total: 4 },
          { name: 'Cargo & Crates', total: 4 },
        ],
      },
      {
        id: 'oop',
        name: 'Object-Oriented Programming',
        icon: '🧱',
        color: '#A29BFE',
        description: 'Core OOP concepts & design patterns',
        topics: [
          { name: 'Classes & Objects', total: 8 },
          { name: 'Inheritance', total: 6 },
          { name: 'Polymorphism', total: 7 },
          { name: 'Abstraction', total: 5 },
          { name: 'Encapsulation', total: 5 },
          { name: 'SOLID Principles', total: 6 },
          { name: 'Design Patterns', total: 15 },
          { name: 'UML', total: 4 },
        ],
      },
      {
        id: 'system-design',
        name: 'System Design',
        icon: '🏗️',
        color: '#FF7675',
        description: 'Design scalable distributed systems',
        topics: [
          { name: 'Scalability Basics', total: 8 },
          { name: 'Load Balancing', total: 5 },
          { name: 'Caching', total: 7 },
          { name: 'Database Sharding', total: 6 },
          { name: 'Message Queues', total: 5 },
          { name: 'Microservices', total: 8 },
          { name: 'API Design', total: 6 },
          { name: 'Rate Limiting', total: 4 },
          { name: 'CAP Theorem', total: 3 },
          { name: 'Case Studies', total: 12 },
        ],
      },
      {
        id: 'competitive-programming',
        name: 'Competitive Programming',
        icon: '🏆',
        color: '#FD79A8',
        description: 'Level up your CP & contest skills',
        topics: [
          { name: 'Number Theory', total: 10 },
          { name: 'Combinatorics', total: 8 },
          { name: 'Graph Algorithms', total: 12 },
          { name: 'DP Patterns', total: 15 },
          { name: 'Geometry', total: 6 },
          { name: 'String Algorithms', total: 8 },
          { name: 'Segment Trees', total: 7 },
          { name: 'Game Theory', total: 5 },
          { name: 'Advanced DS', total: 8 },
        ],
      },
      {
        id: 'sql-programming',
        name: 'SQL Programming',
        icon: '🗃️',
        color: '#336791',
        description: 'Master SQL queries, joins, and database management',
        topics: [
          { name: 'Basics & Syntax', total: 10 },
          { name: 'SELECT & Filtering', total: 12 },
          { name: 'JOINs', total: 10 },
          { name: 'Subqueries', total: 8 },
          { name: 'Aggregation & Grouping', total: 8 },
          { name: 'Window Functions', total: 7 },
          { name: 'Indexing & Optimization', total: 8 },
          { name: 'Stored Procedures', total: 6 },
          { name: 'Transactions', total: 5 },
          { name: 'Database Design', total: 8 },
        ],
      },
      {
        id: 'shell-bash',
        name: 'Shell & Bash Scripting',
        icon: '🖥️',
        color: '#4EAA25',
        description: 'Automate tasks with shell scripting',
        topics: [
          { name: 'Basics & Navigation', total: 8 },
          { name: 'File Operations', total: 7 },
          { name: 'Variables & Arrays', total: 6 },
          { name: 'Control Flow', total: 7 },
          { name: 'Functions', total: 5 },
          { name: 'Text Processing', total: 8 },
          { name: 'Process Management', total: 6 },
          { name: 'Networking Commands', total: 5 },
          { name: 'Cron Jobs', total: 4 },
          { name: 'Advanced Scripting', total: 6 },
        ],
      },
      {
        id: 'scala',
        name: 'Scala Programming',
        icon: '🔴',
        color: '#DC322F',
        description: 'Functional & OOP on the JVM',
        topics: [
          { name: 'Basics & Types', total: 8 },
          { name: 'Functions & Methods', total: 7 },
          { name: 'Collections', total: 9 },
          { name: 'Pattern Matching', total: 6 },
          { name: 'Traits & Mixins', total: 6 },
          { name: 'Concurrency with Akka', total: 7 },
          { name: 'Implicits', total: 5 },
          { name: 'Type System', total: 6 },
          { name: 'Build Tools', total: 4 },
        ],
      },
      {
        id: 'php',
        name: 'PHP Development',
        icon: '🐘',
        color: '#777BB4',
        description: 'Server-side web development with PHP',
        topics: [
          { name: 'Basics & Syntax', total: 10 },
          { name: 'Functions', total: 7 },
          { name: 'OOP in PHP', total: 8 },
          { name: 'Forms & Input', total: 6 },
          { name: 'Database (MySQL)', total: 8 },
          { name: 'Sessions & Cookies', total: 5 },
          { name: 'Error Handling', total: 5 },
          { name: 'Composer & Packages', total: 6 },
          { name: 'Security', total: 6 },
          { name: 'Modern PHP', total: 7 },
        ],
      },
      {
        id: 'kotlin',
        name: 'Kotlin Programming',
        icon: '🟣',
        color: '#7F52FF',
        description: 'Modern JVM language for Android & backend',
        topics: [
          { name: 'Basics & Syntax', total: 8 },
          { name: 'Null Safety', total: 6 },
          { name: 'Functions & Lambdas', total: 7 },
          { name: 'OOP', total: 8 },
          { name: 'Collections', total: 7 },
          { name: 'Coroutines', total: 8 },
          { name: 'Extension Functions', total: 5 },
          { name: 'DSLs', total: 4 },
          { name: 'Multiplatform', total: 5 },
        ],
      },
      {
        id: 'ruby',
        name: 'Ruby Programming',
        icon: '💎',
        color: '#CC342D',
        description: 'Elegant programming with Ruby',
        topics: [
          { name: 'Basics & Syntax', total: 8 },
          { name: 'Data Types', total: 6 },
          { name: 'Control Flow', total: 5 },
          { name: 'Methods & Blocks', total: 7 },
          { name: 'OOP', total: 8 },
          { name: 'Modules & Mixins', total: 6 },
          { name: 'File I/O', total: 4 },
          { name: 'Error Handling', total: 5 },
          { name: 'Gems & Bundler', total: 5 },
          { name: 'Metaprogramming', total: 6 },
        ],
      },
      {
        id: 'html',
        name: 'HTML Fundamentals',
        icon: '📄',
        color: '#E34F26',
        description: 'Structure web pages with semantic HTML',
        topics: [
          { name: 'Basic Tags', total: 8 },
          { name: 'Forms & Input', total: 7 },
          { name: 'Semantic HTML5', total: 8 },
          { name: 'Tables & Lists', total: 5 },
          { name: 'Media Elements', total: 6 },
          { name: 'Accessibility', total: 7 },
          { name: 'SEO Basics', total: 5 },
          { name: 'Canvas & SVG', total: 6 },
          { name: 'Web Components', total: 4 },
        ],
      },
      {
        id: 'css-mastery',
        name: 'CSS Mastery',
        icon: '🎨',
        color: '#1572B6',
        description: 'Style beautiful responsive web interfaces',
        topics: [
          { name: 'Selectors & Specificity', total: 8 },
          { name: 'Box Model', total: 6 },
          { name: 'Flexbox', total: 8 },
          { name: 'CSS Grid', total: 8 },
          { name: 'Responsive Design', total: 7 },
          { name: 'Animations & Transitions', total: 7 },
          { name: 'Variables & Custom Props', total: 5 },
          { name: 'Preprocessors (SASS)', total: 6 },
          { name: 'Modern CSS', total: 6 },
        ],
      },
      {
        id: 'software-architecture',
        name: 'Software Architecture',
        icon: '🏛️',
        color: '#2D3436',
        description: 'Design robust software architectures',
        topics: [
          { name: 'Architecture Patterns', total: 10 },
          { name: 'Microservices', total: 8 },
          { name: 'Event-Driven', total: 7 },
          { name: 'Domain-Driven Design', total: 8 },
          { name: 'CQRS & Event Sourcing', total: 6 },
          { name: 'Clean Architecture', total: 7 },
          { name: 'Architecture Decision Records', total: 4 },
          { name: 'Documentation', total: 5 },
          { name: 'Trade-offs & Evaluation', total: 6 },
        ],
      },
      {
        id: 'software-design-patterns',
        name: 'Software Design Patterns',
        icon: '🧩',
        color: '#636E72',
        description: 'Master software design & architecture patterns',
        topics: [
          { name: 'Creational Patterns', total: 8 },
          { name: 'Structural Patterns', total: 7 },
          { name: 'Behavioral Patterns', total: 8 },
          { name: 'SOLID Principles', total: 6 },
          { name: 'Clean Code', total: 7 },
          { name: 'Refactoring', total: 6 },
          { name: 'Anti-Patterns', total: 5 },
          { name: 'Architectural Patterns', total: 7 },
          { name: 'Functional Patterns', total: 5 },
        ],
      },
      {
        id: 'code-review-mastery',
        name: 'Code Review Mastery',
        icon: '🔍',
        color: '#00B894',
        description: 'Review code effectively and give great feedback',
        topics: [
          { name: 'Review Principles', total: 6 },
          { name: 'Reading Code', total: 5 },
          { name: 'Spotting Bugs', total: 7 },
          { name: 'Performance Issues', total: 6 },
          { name: 'Security Review', total: 6 },
          { name: 'Style & Conventions', total: 5 },
          { name: 'Constructive Feedback', total: 5 },
          { name: 'Automated Tools', total: 5 },
          { name: 'Review Workflows', total: 4 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 2. Artificial Intelligence & ML
  // ─────────────────────────────────────────────
  {
    id: 'ai',
    name: 'Artificial Intelligence & ML',
    icon: '🤖',
    roadmaps: [
      {
        id: 'machine-learning',
        name: 'Machine Learning',
        icon: '🧠',
        color: '#6C5CE7',
        description: 'Classical ML algorithms & techniques',
        topics: [
          { name: 'Linear Regression', total: 8 },
          { name: 'Logistic Regression', total: 6 },
          { name: 'Decision Trees', total: 7 },
          { name: 'Random Forests', total: 5 },
          { name: 'SVM', total: 6 },
          { name: 'KNN', total: 4 },
          { name: 'Clustering', total: 7 },
          { name: 'PCA & Dim. Reduction', total: 5 },
          { name: 'Ensemble Methods', total: 6 },
          { name: 'Model Evaluation', total: 8 },
          { name: 'Feature Engineering', total: 7 },
          { name: 'Regularization', total: 5 },
        ],
      },
      {
        id: 'deep-learning',
        name: 'Deep Learning',
        icon: '🔮',
        color: '#E84393',
        description: 'Neural networks & deep architectures',
        topics: [
          { name: 'Neural Network Basics', total: 10 },
          { name: 'Activation Functions', total: 5 },
          { name: 'Backpropagation', total: 6 },
          { name: 'CNNs', total: 10 },
          { name: 'RNNs & LSTMs', total: 8 },
          { name: 'Transformers', total: 8 },
          { name: 'GANs', total: 6 },
          { name: 'Autoencoders', total: 5 },
          { name: 'Transfer Learning', total: 5 },
          { name: 'Optimization', total: 7 },
        ],
      },
      {
        id: 'artificial-intelligence',
        name: 'Artificial Intelligence',
        icon: '🤯',
        color: '#00B894',
        description: 'Core AI concepts & reasoning systems',
        topics: [
          { name: 'Search Algorithms', total: 8 },
          { name: 'Knowledge Representation', total: 6 },
          { name: 'Probabilistic Reasoning', total: 7 },
          { name: 'Planning', total: 5 },
          { name: 'Expert Systems', total: 4 },
          { name: 'AI Ethics', total: 5 },
          { name: 'Multi-Agent Systems', total: 4 },
        ],
      },
      {
        id: 'nlp',
        name: 'Natural Language Processing',
        icon: '📝',
        color: '#0984E3',
        description: 'Text analysis & language understanding',
        topics: [
          { name: 'Text Preprocessing', total: 8 },
          { name: 'Word Embeddings', total: 6 },
          { name: 'Language Models', total: 7 },
          { name: 'Sentiment Analysis', total: 5 },
          { name: 'Named Entity Recognition', total: 5 },
          { name: 'Machine Translation', total: 6 },
          { name: 'Question Answering', total: 5 },
          { name: 'Summarization', total: 4 },
          { name: 'Chatbots', total: 5 },
        ],
      },
      {
        id: 'computer-vision',
        name: 'Computer Vision',
        icon: '👁️',
        color: '#FDCB6E',
        description: 'Image & video understanding with AI',
        topics: [
          { name: 'Image Processing', total: 8 },
          { name: 'Feature Detection', total: 6 },
          { name: 'Object Detection', total: 8 },
          { name: 'Image Segmentation', total: 7 },
          { name: 'Face Recognition', total: 5 },
          { name: 'Pose Estimation', total: 4 },
          { name: 'Video Analysis', total: 5 },
          { name: 'OCR', total: 4 },
          { name: '3D Vision', total: 5 },
        ],
      },
      {
        id: 'reinforcement-learning',
        name: 'Reinforcement Learning',
        icon: '🎮',
        color: '#FF7675',
        description: 'Agent-based learning & decision making',
        topics: [
          { name: 'MDPs', total: 6 },
          { name: 'Q-Learning', total: 5 },
          { name: 'Policy Gradient', total: 6 },
          { name: 'Actor-Critic', total: 5 },
          { name: 'Multi-Armed Bandits', total: 4 },
          { name: 'Deep RL', total: 7 },
          { name: 'Environments & Gyms', total: 4 },
        ],
      },
      {
        id: 'generative-ai',
        name: 'Generative AI & LLMs',
        icon: '✨',
        color: '#A29BFE',
        description: 'LLMs, prompt engineering & AI agents',
        topics: [
          { name: 'Transformer Architecture', total: 8 },
          { name: 'Prompt Engineering', total: 10 },
          { name: 'Fine-Tuning', total: 6 },
          { name: 'RAG', total: 5 },
          { name: 'LangChain', total: 6 },
          { name: 'Vector Databases', total: 5 },
          { name: 'AI Agents', total: 7 },
          { name: 'Evaluation', total: 5 },
          { name: 'Ethics & Safety', total: 4 },
        ],
      },
      {
        id: 'ai-engineering',
        name: 'AI Engineering',
        icon: '⚙️',
        color: '#FF6B6B',
        description: 'Build and deploy production AI systems',
        topics: [
          { name: 'ML System Design', total: 8 },
          { name: 'Model Serving', total: 7 },
          { name: 'MLOps', total: 8 },
          { name: 'Data Pipelines', total: 7 },
          { name: 'Feature Stores', total: 5 },
          { name: 'Model Monitoring', total: 6 },
          { name: 'A/B Testing', total: 5 },
          { name: 'Infrastructure', total: 6 },
          { name: 'Scaling ML', total: 6 },
          { name: 'Edge AI', total: 4 },
        ],
      },
      {
        id: 'ai-data-science',
        name: 'AI & Data Science',
        icon: '🔬',
        color: '#4ECDC4',
        description: 'Combine AI with data science for insights',
        topics: [
          { name: 'Statistical Learning', total: 8 },
          { name: 'Predictive Modeling', total: 7 },
          { name: 'Deep Learning Applications', total: 8 },
          { name: 'AutoML', total: 5 },
          { name: 'Experiment Tracking', total: 6 },
          { name: 'Model Interpretability', total: 7 },
          { name: 'Time Series', total: 6 },
          { name: 'Recommendation Systems', total: 6 },
          { name: 'Anomaly Detection', total: 5 },
        ],
      },
      {
        id: 'data-analysis-roadmap',
        name: 'Data Analysis',
        icon: '📈',
        color: '#45B7D1',
        description: 'Analyze data to drive business decisions',
        topics: [
          { name: 'Excel & Spreadsheets', total: 8 },
          { name: 'SQL for Analysis', total: 10 },
          { name: 'Python (Pandas)', total: 8 },
          { name: 'Data Visualization', total: 8 },
          { name: 'Statistics', total: 7 },
          { name: 'Reporting & Dashboards', total: 6 },
          { name: 'Data Cleaning', total: 7 },
          { name: 'Storytelling with Data', total: 5 },
          { name: 'BI Tools', total: 6 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 3. Data Science & Analytics
  // ─────────────────────────────────────────────
  {
    id: 'data',
    name: 'Data Science & Analytics',
    icon: '📊',
    roadmaps: [
      {
        id: 'data-science',
        name: 'Data Science',
        icon: '🔬',
        color: '#00CEC9',
        description: 'End-to-end data science workflow',
        topics: [
          { name: 'Statistics Fundamentals', total: 10 },
          { name: 'Probability', total: 8 },
          { name: 'EDA', total: 7 },
          { name: 'Data Cleaning', total: 6 },
          { name: 'Feature Engineering', total: 7 },
          { name: 'Visualization', total: 8 },
          { name: 'Hypothesis Testing', total: 6 },
          { name: 'A/B Testing', total: 5 },
          { name: 'Storytelling with Data', total: 4 },
        ],
      },
      {
        id: 'data-engineering',
        name: 'Data Engineering',
        icon: '🔧',
        color: '#E17055',
        description: 'Build robust data pipelines & infra',
        topics: [
          { name: 'ETL Pipelines', total: 8 },
          { name: 'Data Warehousing', total: 6 },
          { name: 'Apache Spark', total: 8 },
          { name: 'Kafka', total: 5 },
          { name: 'Airflow', total: 6 },
          { name: 'Data Modeling', total: 7 },
          { name: 'Data Quality', total: 5 },
          { name: 'Data Lakes', total: 4 },
        ],
      },
      {
        id: 'data-analytics',
        name: 'Data Analytics',
        icon: '📈',
        color: '#6C5CE7',
        description: 'Analyze data & drive business decisions',
        topics: [
          { name: 'Excel & Spreadsheets', total: 8 },
          { name: 'SQL for Analytics', total: 10 },
          { name: 'Tableau', total: 7 },
          { name: 'Power BI', total: 7 },
          { name: 'Google Analytics', total: 5 },
          { name: 'Cohort Analysis', total: 4 },
          { name: 'Funnel Analysis', total: 4 },
          { name: 'Reporting', total: 5 },
        ],
      },
      {
        id: 'business-intelligence',
        name: 'Business Intelligence',
        icon: '📊',
        color: '#FD79A8',
        description: 'Transform data into actionable insights',
        topics: [
          { name: 'BI Concepts', total: 6 },
          { name: 'Dashboard Design', total: 7 },
          { name: 'KPI Definition', total: 5 },
          { name: 'Data Governance', total: 5 },
          { name: 'Self-Service BI', total: 4 },
          { name: 'Predictive Analytics', total: 6 },
        ],
      },
      {
        id: 'big-data',
        name: 'Big Data',
        icon: '🗃️',
        color: '#0984E3',
        description: 'Process & analyze massive datasets',
        topics: [
          { name: 'Hadoop Ecosystem', total: 8 },
          { name: 'MapReduce', total: 5 },
          { name: 'Hive', total: 5 },
          { name: 'Pig', total: 4 },
          { name: 'HBase', total: 5 },
          { name: 'Spark Streaming', total: 6 },
          { name: 'Data Formats (Parquet/Avro)', total: 4 },
          { name: 'Cloud Big Data', total: 5 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 4. Web Development
  // ─────────────────────────────────────────────
  {
    id: 'web',
    name: 'Web Development',
    icon: '🌐',
    roadmaps: [
      {
        id: 'frontend',
        name: 'Frontend Development',
        icon: '🎨',
        color: '#E84393',
        description: 'Build modern, responsive web UIs',
        topics: [
          { name: 'HTML5 Semantic', total: 10 },
          { name: 'CSS3 & Flexbox/Grid', total: 12 },
          { name: 'JavaScript Fundamentals', total: 10 },
          { name: 'Responsive Design', total: 6 },
          { name: 'Accessibility', total: 5 },
          { name: 'Browser DevTools', total: 4 },
          { name: 'Performance Optimization', total: 6 },
          { name: 'Build Tools', total: 5 },
        ],
      },
      {
        id: 'react-nextjs',
        name: 'React & Next.js',
        icon: '⚛️',
        color: '#00B894',
        description: 'Full-stack React with Next.js',
        topics: [
          { name: 'JSX & Components', total: 8 },
          { name: 'State & Props', total: 7 },
          { name: 'Hooks', total: 10 },
          { name: 'Context & Redux', total: 7 },
          { name: 'Routing', total: 5 },
          { name: 'Server Components', total: 6 },
          { name: 'API Routes', total: 5 },
          { name: 'SSR/SSG/ISR', total: 6 },
          { name: 'Deployment', total: 4 },
        ],
      },
      {
        id: 'backend',
        name: 'Backend Development',
        icon: '🖥️',
        color: '#6C5CE7',
        description: 'Server-side APIs & architecture',
        topics: [
          { name: 'Node.js & Express', total: 10 },
          { name: 'REST API Design', total: 8 },
          { name: 'Authentication', total: 7 },
          { name: 'Database Integration', total: 8 },
          { name: 'Middleware', total: 5 },
          { name: 'Error Handling', total: 5 },
          { name: 'File Uploads', total: 4 },
          { name: 'Caching', total: 5 },
          { name: 'Testing', total: 6 },
        ],
      },
      {
        id: 'fullstack',
        name: 'Full-Stack Development',
        icon: '🔗',
        color: '#FDCB6E',
        description: 'End-to-end web app development',
        topics: [
          { name: 'Architecture Patterns', total: 7 },
          { name: 'Frontend-Backend Integration', total: 6 },
          { name: 'Deployment & CI/CD', total: 6 },
          { name: 'Monorepo Management', total: 4 },
          { name: 'WebSockets', total: 5 },
          { name: 'Payment Integration', total: 4 },
          { name: 'Email/Notifications', total: 4 },
        ],
      },
      {
        id: 'typescript',
        name: 'TypeScript',
        icon: '🔷',
        color: '#0984E3',
        description: 'Type-safe JavaScript development',
        topics: [
          { name: 'Type System', total: 8 },
          { name: 'Interfaces & Types', total: 7 },
          { name: 'Generics', total: 6 },
          { name: 'Utility Types', total: 5 },
          { name: 'Decorators', total: 4 },
          { name: 'Module System', total: 4 },
          { name: 'Config & Tooling', total: 4 },
          { name: 'Advanced Patterns', total: 6 },
        ],
      },
      {
        id: 'web-apis-graphql',
        name: 'Web APIs & GraphQL',
        icon: '🔌',
        color: '#FF7675',
        description: 'Design & consume modern web APIs',
        topics: [
          { name: 'REST Principles', total: 6 },
          { name: 'GraphQL Basics', total: 7 },
          { name: 'Apollo Client/Server', total: 6 },
          { name: 'API Authentication', total: 5 },
          { name: 'Rate Limiting', total: 4 },
          { name: 'Webhooks', total: 4 },
          { name: 'OpenAPI/Swagger', total: 4 },
          { name: 'WebSockets', total: 5 },
        ],
      },
      {
        id: 'qa-engineering',
        name: 'QA Engineering',
        icon: '✅',
        color: '#27AE60',
        description: 'Quality assurance testing & automation',
        topics: [
          { name: 'Testing Fundamentals', total: 8 },
          { name: 'Manual Testing', total: 7 },
          { name: 'Test Automation', total: 10 },
          { name: 'Selenium & Cypress', total: 8 },
          { name: 'API Testing', total: 7 },
          { name: 'Performance Testing', total: 6 },
          { name: 'CI/CD Integration', total: 6 },
          { name: 'Test Planning', total: 5 },
          { name: 'Mobile Testing', total: 5 },
          { name: 'Security Testing', total: 5 },
        ],
      },
      {
        id: 'api-design',
        name: 'API Design & Development',
        icon: '🔗',
        color: '#3498DB',
        description: 'Design RESTful & scalable APIs',
        topics: [
          { name: 'REST Principles', total: 8 },
          { name: 'HTTP Methods & Status Codes', total: 6 },
          { name: 'URL Design', total: 5 },
          { name: 'Authentication', total: 7 },
          { name: 'Rate Limiting', total: 5 },
          { name: 'Versioning', total: 4 },
          { name: 'Documentation', total: 6 },
          { name: 'Error Handling', total: 5 },
          { name: 'Pagination & Filtering', total: 5 },
          { name: 'API Gateway', total: 5 },
        ],
      },
      {
        id: 'graphql-dev',
        name: 'GraphQL Development',
        icon: '▲',
        color: '#E535AB',
        description: 'Build flexible APIs with GraphQL',
        topics: [
          { name: 'Schema & Types', total: 8 },
          { name: 'Queries & Mutations', total: 7 },
          { name: 'Resolvers', total: 7 },
          { name: 'Subscriptions', total: 5 },
          { name: 'Authentication', total: 5 },
          { name: 'Pagination', total: 4 },
          { name: 'Error Handling', total: 5 },
          { name: 'Apollo & Relay', total: 6 },
          { name: 'Performance', total: 5 },
          { name: 'Federation', total: 4 },
        ],
      },
      {
        id: 'git-github',
        name: 'Git & GitHub Mastery',
        icon: '🔀',
        color: '#F05032',
        description: 'Version control & collaborative development',
        topics: [
          { name: 'Git Basics', total: 8 },
          { name: 'Branching & Merging', total: 7 },
          { name: 'Rebasing', total: 5 },
          { name: 'Git Flow', total: 6 },
          { name: 'Pull Requests', total: 6 },
          { name: 'Code Review on GitHub', total: 5 },
          { name: 'GitHub Actions', total: 7 },
          { name: 'Conflict Resolution', total: 5 },
          { name: 'Advanced Git', total: 5 },
          { name: 'Open Source Contribution', total: 5 },
        ],
      },
      {
        id: 'wordpress',
        name: 'WordPress Development',
        icon: '📝',
        color: '#21759B',
        description: 'Build sites & plugins with WordPress',
        topics: [
          { name: 'WordPress Setup', total: 6 },
          { name: 'Themes', total: 8 },
          { name: 'Plugins', total: 8 },
          { name: 'Custom Post Types', total: 6 },
          { name: 'WooCommerce', total: 7 },
          { name: 'REST API', total: 6 },
          { name: 'Security', total: 5 },
          { name: 'Performance', total: 5 },
          { name: 'Gutenberg Blocks', total: 6 },
          { name: 'Deployment', total: 4 },
        ],
      },
      {
        id: 'fde',
        name: 'Forward Deployed Engineer',
        icon: '🚀',
        color: '#E67E22',
        description: 'Customer-facing engineering & technical sales',
        topics: [
          { name: 'Technical Communication', total: 7 },
          { name: 'Rapid Prototyping', total: 6 },
          { name: 'Customer Discovery', total: 6 },
          { name: 'Demo Engineering', total: 5 },
          { name: 'Solution Architecture', total: 7 },
          { name: 'Integration Patterns', total: 6 },
          { name: 'Deployment Strategies', total: 5 },
          { name: 'Debugging in Production', total: 5 },
          { name: 'Stakeholder Management', total: 5 },
        ],
      },
      {
        id: 'vue',
        name: 'Vue.js Development',
        icon: '🟢',
        color: '#42B883',
        description: 'Build reactive UIs with Vue.js',
        topics: [
          { name: 'Vue Basics', total: 8 },
          { name: 'Components', total: 8 },
          { name: 'Reactivity System', total: 7 },
          { name: 'Vue Router', total: 6 },
          { name: 'Vuex/Pinia', total: 7 },
          { name: 'Composition API', total: 7 },
          { name: 'Directives', total: 5 },
          { name: 'Lifecycle Hooks', total: 5 },
          { name: 'Testing', total: 5 },
          { name: 'Nuxt.js', total: 6 },
        ],
      },
      {
        id: 'angular',
        name: 'Angular Development',
        icon: '🟥',
        color: '#DD0031',
        description: 'Enterprise web apps with Angular',
        topics: [
          { name: 'TypeScript Basics', total: 7 },
          { name: 'Components & Templates', total: 8 },
          { name: 'Directives & Pipes', total: 6 },
          { name: 'Services & DI', total: 7 },
          { name: 'Routing', total: 6 },
          { name: 'Forms', total: 7 },
          { name: 'HTTP Client', total: 6 },
          { name: 'RxJS & Observables', total: 8 },
          { name: 'Testing', total: 6 },
          { name: 'NgModules & Standalone', total: 5 },
        ],
      },
      {
        id: 'aspnet-core',
        name: 'ASP.NET Core',
        icon: '🟦',
        color: '#512BD4',
        description: 'Build web apps with .NET & C#',
        topics: [
          { name: 'C# Fundamentals', total: 8 },
          { name: 'MVC Pattern', total: 7 },
          { name: 'Razor Pages', total: 6 },
          { name: 'Web API', total: 7 },
          { name: 'Entity Framework', total: 8 },
          { name: 'Identity & Auth', total: 6 },
          { name: 'Middleware', total: 5 },
          { name: 'SignalR', total: 5 },
          { name: 'Blazor', total: 6 },
          { name: 'Deployment', total: 5 },
        ],
      },
      {
        id: 'spring-boot',
        name: 'Spring Boot',
        icon: '🌿',
        color: '#6DB33F',
        description: 'Java enterprise applications with Spring',
        topics: [
          { name: 'Spring Core & DI', total: 8 },
          { name: 'Spring Boot Basics', total: 7 },
          { name: 'REST APIs', total: 7 },
          { name: 'Spring Data JPA', total: 7 },
          { name: 'Security', total: 7 },
          { name: 'Spring MVC', total: 6 },
          { name: 'Testing', total: 6 },
          { name: 'Microservices', total: 7 },
          { name: 'Spring Cloud', total: 6 },
          { name: 'Actuator & Monitoring', total: 5 },
        ],
      },
      {
        id: 'nextjs',
        name: 'Next.js Development',
        icon: '▶️',
        color: '#000000',
        description: 'Full-stack React framework',
        topics: [
          { name: 'Pages & Routing', total: 7 },
          { name: 'SSR vs SSG', total: 7 },
          { name: 'API Routes', total: 6 },
          { name: 'Data Fetching', total: 7 },
          { name: 'App Router', total: 7 },
          { name: 'Server Components', total: 6 },
          { name: 'Middleware', total: 5 },
          { name: 'Image Optimization', total: 5 },
          { name: 'Authentication', total: 6 },
          { name: 'Deployment & Vercel', total: 5 },
        ],
      },
      {
        id: 'laravel',
        name: 'Laravel Development',
        icon: '🔶',
        color: '#FF2D20',
        description: 'Elegant PHP web application framework',
        topics: [
          { name: 'Routing & Controllers', total: 7 },
          { name: 'Blade Templates', total: 6 },
          { name: 'Eloquent ORM', total: 8 },
          { name: 'Migrations', total: 6 },
          { name: 'Authentication', total: 6 },
          { name: 'Middleware', total: 5 },
          { name: 'Queues & Jobs', total: 6 },
          { name: 'Testing', total: 5 },
          { name: 'APIs & Resources', total: 6 },
          { name: 'Deployment', total: 4 },
        ],
      },
      {
        id: 'django',
        name: 'Django Development',
        icon: '🐍',
        color: '#092E20',
        description: 'Python web framework for rapid development',
        topics: [
          { name: 'Models & ORM', total: 8 },
          { name: 'Views & URLs', total: 7 },
          { name: 'Templates', total: 6 },
          { name: 'Forms', total: 6 },
          { name: 'Admin Interface', total: 5 },
          { name: 'Authentication', total: 6 },
          { name: 'REST Framework', total: 7 },
          { name: 'Middleware', total: 5 },
          { name: 'Testing', total: 5 },
          { name: 'Deployment', total: 5 },
        ],
      },
      {
        id: 'ruby-on-rails',
        name: 'Ruby on Rails',
        icon: '🛤️',
        color: '#CC0000',
        description: 'Full-stack web development with Rails',
        topics: [
          { name: 'MVC Architecture', total: 7 },
          { name: 'Active Record', total: 8 },
          { name: 'Routing', total: 6 },
          { name: 'Views & ERB', total: 6 },
          { name: 'Migrations', total: 6 },
          { name: 'Authentication (Devise)', total: 5 },
          { name: 'Testing (RSpec)', total: 6 },
          { name: 'Action Cable', total: 5 },
          { name: 'Active Job', total: 5 },
          { name: 'Deployment', total: 5 },
        ],
      },
      {
        id: 'frontend-beginner',
        name: 'Frontend Beginner',
        icon: '🌱',
        color: '#55EFC4',
        description: 'Start your frontend development journey',
        topics: [
          { name: 'HTML Basics', total: 10 },
          { name: 'CSS Basics', total: 10 },
          { name: 'JavaScript Basics', total: 12 },
          { name: 'DOM Manipulation', total: 8 },
          { name: 'Responsive Design', total: 7 },
          { name: 'Basic Projects', total: 8 },
          { name: 'Browser DevTools', total: 5 },
          { name: 'Version Control', total: 5 },
          { name: 'Deployment Basics', total: 4 },
        ],
      },
      {
        id: 'backend-beginner',
        name: 'Backend Beginner',
        icon: '🌱',
        color: '#81ECEC',
        description: 'Start your backend development journey',
        topics: [
          { name: 'How the Web Works', total: 8 },
          { name: 'Your First Server', total: 7 },
          { name: 'Routes & Endpoints', total: 7 },
          { name: 'Database Basics', total: 8 },
          { name: 'CRUD Operations', total: 8 },
          { name: 'Authentication Basics', total: 6 },
          { name: 'REST Basics', total: 6 },
          { name: 'Error Handling', total: 5 },
          { name: 'Deployment Basics', total: 5 },
        ],
      },
      {
        id: 'devops-beginner',
        name: 'DevOps Beginner',
        icon: '🌱',
        color: '#A3CB38',
        description: 'Start your DevOps journey',
        topics: [
          { name: 'Linux Basics', total: 8 },
          { name: 'Shell Scripting', total: 6 },
          { name: 'Networking Fundamentals', total: 7 },
          { name: 'Version Control', total: 5 },
          { name: 'CI/CD Concepts', total: 7 },
          { name: 'Containers Intro', total: 6 },
          { name: 'Cloud Basics', total: 6 },
          { name: 'Monitoring Basics', total: 5 },
          { name: 'Infrastructure as Code', total: 5 },
        ],
      }
    ],
  },

  // ─────────────────────────────────────────────
  // 5. Mobile Development
  // ─────────────────────────────────────────────
  {
    id: 'mobile',
    name: 'Mobile Development',
    icon: '📱',
    roadmaps: [
      {
        id: 'android',
        name: 'Android Development',
        icon: '🤖',
        color: '#00B894',
        description: 'Native Android apps with Kotlin',
        topics: [
          { name: 'Kotlin Basics', total: 10 },
          { name: 'Activities & Fragments', total: 8 },
          { name: 'Jetpack Compose', total: 10 },
          { name: 'Navigation', total: 6 },
          { name: 'Networking (Retrofit)', total: 5 },
          { name: 'Room Database', total: 6 },
          { name: 'MVVM Architecture', total: 5 },
          { name: 'Notifications', total: 4 },
          { name: 'App Publishing', total: 4 },
        ],
      },
      {
        id: 'ios',
        name: 'iOS Development',
        icon: '🍎',
        color: '#0984E3',
        description: 'Native iOS apps with Swift & SwiftUI',
        topics: [
          { name: 'Swift Basics', total: 10 },
          { name: 'SwiftUI', total: 10 },
          { name: 'UIKit', total: 8 },
          { name: 'Core Data', total: 6 },
          { name: 'Networking', total: 5 },
          { name: 'Combine Framework', total: 5 },
          { name: 'App Architecture', total: 6 },
          { name: 'TestFlight & Publishing', total: 4 },
        ],
      },
      {
        id: 'flutter',
        name: 'Flutter & Dart',
        icon: '🦋',
        color: '#00CEC9',
        description: 'Cross-platform apps with Flutter',
        topics: [
          { name: 'Dart Basics', total: 8 },
          { name: 'Widgets', total: 10 },
          { name: 'State Management', total: 8 },
          { name: 'Navigation & Routing', total: 5 },
          { name: 'HTTP & APIs', total: 5 },
          { name: 'Local Storage', total: 4 },
          { name: 'Animations', total: 6 },
          { name: 'Platform Channels', total: 4 },
          { name: 'Publishing', total: 3 },
        ],
      },
      {
        id: 'react-native',
        name: 'React Native',
        icon: '📲',
        color: '#6C5CE7',
        description: 'Cross-platform mobile with React',
        topics: [
          { name: 'Setup & Environment', total: 5 },
          { name: 'Components & Styling', total: 8 },
          { name: 'Navigation', total: 6 },
          { name: 'State Management', total: 6 },
          { name: 'Native Modules', total: 5 },
          { name: 'APIs & Networking', total: 5 },
          { name: 'Debugging', total: 4 },
          { name: 'Publishing', total: 4 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 6. Cloud & DevOps
  // ─────────────────────────────────────────────
  {
    id: 'cloud',
    name: 'Cloud & DevOps',
    icon: '☁️',
    roadmaps: [
      {
        id: 'aws',
        name: 'AWS Cloud',
        icon: '🔶',
        color: '#E17055',
        description: 'Amazon Web Services core services',
        topics: [
          { name: 'IAM', total: 6 },
          { name: 'EC2', total: 7 },
          { name: 'S3', total: 5 },
          { name: 'Lambda', total: 6 },
          { name: 'RDS', total: 5 },
          { name: 'DynamoDB', total: 5 },
          { name: 'VPC', total: 6 },
          { name: 'CloudFormation', total: 5 },
          { name: 'API Gateway', total: 4 },
          { name: 'SQS/SNS', total: 5 },
        ],
      },
      {
        id: 'azure',
        name: 'Azure Cloud',
        icon: '🔵',
        color: '#0984E3',
        description: 'Microsoft Azure cloud platform',
        topics: [
          { name: 'Azure Fundamentals', total: 8 },
          { name: 'VMs', total: 5 },
          { name: 'App Services', total: 6 },
          { name: 'Azure Functions', total: 5 },
          { name: 'Cosmos DB', total: 5 },
          { name: 'Azure DevOps', total: 6 },
          { name: 'Networking', total: 5 },
          { name: 'Storage', total: 4 },
        ],
      },
      {
        id: 'gcp',
        name: 'Google Cloud',
        icon: '🌈',
        color: '#FDCB6E',
        description: 'Google Cloud Platform essentials',
        topics: [
          { name: 'GCP Fundamentals', total: 8 },
          { name: 'Compute Engine', total: 5 },
          { name: 'Cloud Functions', total: 5 },
          { name: 'BigQuery', total: 6 },
          { name: 'Cloud Storage', total: 4 },
          { name: 'Kubernetes Engine', total: 6 },
          { name: 'Pub/Sub', total: 4 },
          { name: 'IAM', total: 4 },
        ],
      },
      {
        id: 'devops',
        name: 'DevOps & CI/CD',
        icon: '🔄',
        color: '#6C5CE7',
        description: 'Automate builds, deploys & operations',
        topics: [
          { name: 'Git Advanced', total: 8 },
          { name: 'GitHub Actions', total: 6 },
          { name: 'Jenkins', total: 5 },
          { name: 'GitLab CI', total: 5 },
          { name: 'ArgoCD', total: 4 },
          { name: 'Infrastructure as Code', total: 6 },
          { name: 'Monitoring', total: 6 },
          { name: 'Incident Management', total: 4 },
        ],
      },
      {
        id: 'docker-k8s',
        name: 'Docker & Kubernetes',
        icon: '🐳',
        color: '#00B894',
        description: 'Containerization & orchestration',
        topics: [
          { name: 'Docker Basics', total: 8 },
          { name: 'Dockerfile', total: 5 },
          { name: 'Docker Compose', total: 6 },
          { name: 'K8s Architecture', total: 7 },
          { name: 'Pods & Services', total: 6 },
          { name: 'Deployments', total: 5 },
          { name: 'Helm Charts', total: 5 },
          { name: 'Service Mesh', total: 4 },
          { name: 'Monitoring', total: 4 },
        ],
      },
      {
        id: 'linux',
        name: 'Linux Administration',
        icon: '🐧',
        color: '#A29BFE',
        description: 'Master the Linux command line & admin',
        topics: [
          { name: 'Command Line', total: 10 },
          { name: 'File System', total: 6 },
          { name: 'Users & Permissions', total: 6 },
          { name: 'Process Management', total: 5 },
          { name: 'Shell Scripting', total: 8 },
          { name: 'Networking', total: 6 },
          { name: 'Package Management', total: 4 },
          { name: 'System Monitoring', total: 5 },
          { name: 'Security', total: 5 },
        ],
      },
      {
        id: 'terraform',
        name: 'Terraform',
        icon: '🏚️',
        color: '#7B42BC',
        description: 'Infrastructure as Code with Terraform',
        topics: [
          { name: 'HCL Basics', total: 8 },
          { name: 'Providers', total: 7 },
          { name: 'Resources & Data Sources', total: 8 },
          { name: 'Variables & Outputs', total: 6 },
          { name: 'State Management', total: 7 },
          { name: 'Modules', total: 7 },
          { name: 'Workspaces', total: 5 },
          { name: 'Terraform Cloud', total: 5 },
          { name: 'Best Practices', total: 6 },
          { name: 'CI/CD Integration', total: 5 },
        ],
      },
      {
        id: 'cloudflare',
        name: 'Cloudflare',
        icon: '☁️',
        color: '#F38020',
        description: 'Edge computing & CDN with Cloudflare',
        topics: [
          { name: 'DNS Management', total: 7 },
          { name: 'CDN & Caching', total: 6 },
          { name: 'Workers', total: 8 },
          { name: 'Pages', total: 6 },
          { name: 'R2 Storage', total: 5 },
          { name: 'Security (WAF)', total: 7 },
          { name: 'SSL/TLS', total: 5 },
          { name: 'Load Balancing', total: 5 },
          { name: 'Analytics', total: 4 },
          { name: 'Zero Trust', total: 5 },
        ],
      },
      {
        id: 'devsecops',
        name: 'DevSecOps',
        icon: '🔐',
        color: '#FF6348',
        description: 'Integrate security into DevOps pipelines',
        topics: [
          { name: 'Security in CI/CD', total: 8 },
          { name: 'SAST & DAST', total: 7 },
          { name: 'Container Security', total: 7 },
          { name: 'Secret Management', total: 6 },
          { name: 'Compliance as Code', total: 6 },
          { name: 'Threat Modeling', total: 6 },
          { name: 'Vulnerability Management', total: 7 },
          { name: 'Supply Chain Security', total: 5 },
          { name: 'Incident Response', total: 5 },
          { name: 'Security Automation', total: 5 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 7. Cybersecurity
  // ─────────────────────────────────────────────
  {
    id: 'security',
    name: 'Cybersecurity',
    icon: '🔒',
    roadmaps: [
      {
        id: 'cybersecurity-fundamentals',
        name: 'Cybersecurity Fundamentals',
        icon: '🛡️',
        color: '#E84393',
        description: 'Core security concepts & frameworks',
        topics: [
          { name: 'CIA Triad', total: 4 },
          { name: 'Network Security Basics', total: 7 },
          { name: 'Security Policies', total: 5 },
          { name: 'Risk Assessment', total: 6 },
          { name: 'Incident Response', total: 6 },
          { name: 'Security Frameworks', total: 5 },
          { name: 'Compliance', total: 5 },
        ],
      },
      {
        id: 'ethical-hacking',
        name: 'Ethical Hacking',
        icon: '🎭',
        color: '#00CEC9',
        description: 'Penetration testing & offensive sec',
        topics: [
          { name: 'Reconnaissance', total: 7 },
          { name: 'Scanning & Enumeration', total: 8 },
          { name: 'Exploitation', total: 10 },
          { name: 'Post-Exploitation', total: 6 },
          { name: 'Web App Hacking', total: 8 },
          { name: 'Social Engineering', total: 5 },
          { name: 'Report Writing', total: 4 },
        ],
      },
      {
        id: 'network-security',
        name: 'Network Security',
        icon: '🌐',
        color: '#6C5CE7',
        description: 'Protect networks & communications',
        topics: [
          { name: 'Firewalls', total: 6 },
          { name: 'IDS/IPS', total: 5 },
          { name: 'VPN', total: 4 },
          { name: 'Network Protocols', total: 7 },
          { name: 'Wireless Security', total: 5 },
          { name: 'DDoS Protection', total: 4 },
          { name: 'Zero Trust', total: 4 },
        ],
      },
      {
        id: 'cryptography',
        name: 'Cryptography',
        icon: '🔐',
        color: '#FDCB6E',
        description: 'Encryption, hashing & digital certs',
        topics: [
          { name: 'Symmetric Encryption', total: 6 },
          { name: 'Asymmetric Encryption', total: 6 },
          { name: 'Hashing', total: 5 },
          { name: 'Digital Signatures', total: 4 },
          { name: 'PKI', total: 5 },
          { name: 'TLS/SSL', total: 5 },
          { name: 'Blockchain Cryptography', total: 4 },
        ],
      },
      {
        id: 'application-security',
        name: 'Application Security',
        icon: '🔍',
        color: '#FF7675',
        description: 'Secure coding & app vulnerability mgmt',
        topics: [
          { name: 'OWASP Top 10', total: 10 },
          { name: 'Secure Coding', total: 7 },
          { name: 'Input Validation', total: 5 },
          { name: 'Auth & Session Mgmt', total: 6 },
          { name: 'API Security', total: 5 },
          { name: 'Code Review', total: 4 },
          { name: 'SAST/DAST', total: 4 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 8. Database & Systems
  // ─────────────────────────────────────────────
  {
    id: 'systems',
    name: 'Database & Systems',
    icon: '🗄️',
    roadmaps: [
      {
        id: 'sql',
        name: 'SQL & Relational Databases',
        icon: '🗃️',
        color: '#0984E3',
        description: 'Master SQL queries & RDBMS concepts',
        topics: [
          { name: 'SQL Basics', total: 10 },
          { name: 'Joins', total: 8 },
          { name: 'Subqueries', total: 6 },
          { name: 'Indexing', total: 5 },
          { name: 'Normalization', total: 6 },
          { name: 'Transactions', total: 5 },
          { name: 'Stored Procedures', total: 5 },
          { name: 'Query Optimization', total: 6 },
          { name: 'PostgreSQL', total: 5 },
        ],
      },
      {
        id: 'nosql',
        name: 'NoSQL Databases',
        icon: '📦',
        color: '#00B894',
        description: 'Document, key-value & graph databases',
        topics: [
          { name: 'MongoDB Basics', total: 8 },
          { name: 'Document Model', total: 5 },
          { name: 'Aggregation', total: 6 },
          { name: 'Redis', total: 6 },
          { name: 'Cassandra', total: 5 },
          { name: 'DynamoDB', total: 4 },
          { name: 'Graph Databases (Neo4j)', total: 5 },
        ],
      },
      {
        id: 'operating-systems',
        name: 'Operating Systems',
        icon: '💽',
        color: '#E17055',
        description: 'OS internals & resource management',
        topics: [
          { name: 'Process Management', total: 8 },
          { name: 'Threads', total: 6 },
          { name: 'CPU Scheduling', total: 7 },
          { name: 'Deadlocks', total: 5 },
          { name: 'Memory Management', total: 8 },
          { name: 'Virtual Memory', total: 5 },
          { name: 'File Systems', total: 6 },
          { name: 'I/O Systems', total: 5 },
        ],
      },
      {
        id: 'computer-networks',
        name: 'Computer Networks',
        icon: '🌍',
        color: '#6C5CE7',
        description: 'Networking protocols & architecture',
        topics: [
          { name: 'OSI Model', total: 7 },
          { name: 'TCP/IP', total: 6 },
          { name: 'HTTP/HTTPS', total: 5 },
          { name: 'DNS', total: 4 },
          { name: 'Routing', total: 6 },
          { name: 'Subnetting', total: 5 },
          { name: 'Network Security', total: 5 },
          { name: 'Socket Programming', total: 5 },
          { name: 'Wireless', total: 4 },
        ],
      },
      {
        id: 'distributed-systems',
        name: 'Distributed Systems',
        icon: '🌐',
        color: '#A29BFE',
        description: 'Build reliable distributed architectures',
        topics: [
          { name: 'Consistency Models', total: 6 },
          { name: 'Consensus Algorithms', total: 5 },
          { name: 'Replication', total: 5 },
          { name: 'Partitioning', total: 5 },
          { name: 'Distributed Transactions', total: 4 },
          { name: 'MapReduce', total: 4 },
          { name: 'Clock Synchronization', total: 3 },
          { name: 'Fault Tolerance', total: 5 },
        ],
      },
      {
        id: 'compiler-design',
        name: 'Compiler Design',
        icon: '⚙️',
        color: '#FD79A8',
        description: 'Build compilers & language parsers',
        topics: [
          { name: 'Lexical Analysis', total: 6 },
          { name: 'Syntax Analysis', total: 7 },
          { name: 'Semantic Analysis', total: 5 },
          { name: 'Intermediate Code', total: 5 },
          { name: 'Code Optimization', total: 6 },
          { name: 'Code Generation', total: 5 },
          { name: 'Runtime Environments', total: 4 },
        ],
      },
      {
        id: 'mongodb',
        name: 'MongoDB',
        icon: '🍃',
        color: '#47A248',
        description: 'Document database for modern applications',
        topics: [
          { name: 'CRUD Operations', total: 8 },
          { name: 'Data Modeling', total: 7 },
          { name: 'Indexing', total: 7 },
          { name: 'Aggregation Pipeline', total: 8 },
          { name: 'Replication', total: 6 },
          { name: 'Sharding', total: 6 },
          { name: 'Security', total: 5 },
          { name: 'Performance Tuning', total: 6 },
          { name: 'Atlas Cloud', total: 5 },
          { name: 'Transactions', total: 5 },
        ],
      },
      {
        id: 'redis',
        name: 'Redis',
        icon: '⚡',
        color: '#DC382D',
        description: 'In-memory data store & cache',
        topics: [
          { name: 'Data Structures', total: 8 },
          { name: 'Caching Patterns', total: 7 },
          { name: 'Pub/Sub', total: 5 },
          { name: 'Transactions', total: 5 },
          { name: 'Persistence', total: 6 },
          { name: 'Replication & Sentinel', total: 6 },
          { name: 'Cluster Mode', total: 6 },
          { name: 'Streams', total: 5 },
          { name: 'Lua Scripting', total: 4 },
          { name: 'Best Practices', total: 5 },
        ],
      },
      {
        id: 'elasticsearch',
        name: 'Elasticsearch',
        icon: '🔍',
        color: '#FEC514',
        description: 'Search & analytics engine',
        topics: [
          { name: 'Index Management', total: 7 },
          { name: 'Mappings & Types', total: 6 },
          { name: 'Query DSL', total: 8 },
          { name: 'Aggregations', total: 7 },
          { name: 'Analyzers & Tokenizers', total: 6 },
          { name: 'Cluster Management', total: 6 },
          { name: 'Performance', total: 6 },
          { name: 'Kibana', total: 5 },
          { name: 'Logstash', total: 5 },
          { name: 'ELK Stack', total: 5 },
        ],
      },
      {
        id: 'postgresql-dba',
        name: 'PostgreSQL DBA',
        icon: '🐘',
        color: '#336791',
        description: 'PostgreSQL database administration',
        topics: [
          { name: 'Installation & Setup', total: 6 },
          { name: 'SQL Fundamentals', total: 8 },
          { name: 'Data Types', total: 6 },
          { name: 'Indexing Strategies', total: 7 },
          { name: 'Query Optimization', total: 8 },
          { name: 'Replication', total: 6 },
          { name: 'Backup & Recovery', total: 6 },
          { name: 'Security', total: 5 },
          { name: 'Extensions', total: 5 },
          { name: 'Monitoring & Tuning', total: 6 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 9. Mathematics
  // ─────────────────────────────────────────────
  {
    id: 'math',
    name: 'Mathematics',
    icon: '📐',
    roadmaps: [
      {
        id: 'discrete-math',
        name: 'Discrete Mathematics',
        icon: '🔢',
        color: '#6C5CE7',
        description: 'Foundations for CS & algorithms',
        topics: [
          { name: 'Set Theory', total: 6 },
          { name: 'Logic', total: 7 },
          { name: 'Relations', total: 5 },
          { name: 'Functions', total: 5 },
          { name: 'Graph Theory', total: 8 },
          { name: 'Combinatorics', total: 7 },
          { name: 'Recurrence Relations', total: 5 },
          { name: 'Boolean Algebra', total: 4 },
        ],
      },
      {
        id: 'linear-algebra',
        name: 'Linear Algebra',
        icon: '📊',
        color: '#00CEC9',
        description: 'Vectors, matrices & transformations',
        topics: [
          { name: 'Vectors', total: 6 },
          { name: 'Matrices', total: 8 },
          { name: 'Systems of Equations', total: 5 },
          { name: 'Eigenvalues', total: 6 },
          { name: 'Vector Spaces', total: 5 },
          { name: 'Linear Transformations', total: 5 },
          { name: 'SVD', total: 4 },
          { name: 'Applications in ML', total: 5 },
        ],
      },
      {
        id: 'probability-statistics',
        name: 'Probability & Statistics',
        icon: '🎲',
        color: '#E84393',
        description: 'Statistical analysis & probability',
        topics: [
          { name: 'Probability Basics', total: 8 },
          { name: 'Random Variables', total: 6 },
          { name: 'Distributions', total: 8 },
          { name: 'Bayes Theorem', total: 4 },
          { name: 'Hypothesis Testing', total: 6 },
          { name: 'Regression', total: 5 },
          { name: 'Confidence Intervals', total: 4 },
          { name: 'Bayesian Stats', total: 5 },
        ],
      },
      {
        id: 'calculus',
        name: 'Calculus',
        icon: '∫',
        color: '#E17055',
        description: 'Derivatives, integrals & beyond',
        topics: [
          { name: 'Limits', total: 6 },
          { name: 'Derivatives', total: 8 },
          { name: 'Integration', total: 8 },
          { name: 'Multivariable Calculus', total: 7 },
          { name: 'Differential Equations', total: 6 },
          { name: 'Series & Sequences', total: 5 },
          { name: 'Vector Calculus', total: 5 },
        ],
      },
      {
        id: 'number-theory',
        name: 'Number Theory',
        icon: '🔣',
        color: '#FDCB6E',
        description: 'Properties of integers & primes',
        topics: [
          { name: 'Divisibility', total: 5 },
          { name: 'Primes', total: 6 },
          { name: 'Modular Arithmetic', total: 6 },
          { name: 'GCD & LCM', total: 4 },
          { name: "Euler's Theorem", total: 4 },
          { name: 'Chinese Remainder', total: 3 },
          { name: 'Cryptographic Applications', total: 4 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 10. Design & Creative
  // ─────────────────────────────────────────────
  {
    id: 'design',
    name: 'Design & Creative',
    icon: '🎨',
    roadmaps: [
      {
        id: 'ui-ux',
        name: 'UI/UX Design',
        icon: '🎯',
        color: '#E84393',
        description: 'User-centered design & prototyping',
        topics: [
          { name: 'Design Thinking', total: 6 },
          { name: 'User Research', total: 7 },
          { name: 'Wireframing', total: 5 },
          { name: 'Prototyping', total: 6 },
          { name: 'Visual Design', total: 8 },
          { name: 'Typography', total: 5 },
          { name: 'Color Theory', total: 5 },
          { name: 'Usability Testing', total: 5 },
          { name: 'Design Systems', total: 6 },
        ],
      },
      {
        id: 'graphic-design',
        name: 'Graphic Design',
        icon: '🖌️',
        color: '#FF7675',
        description: 'Visual design & branding essentials',
        topics: [
          { name: 'Adobe Photoshop', total: 8 },
          { name: 'Illustrator', total: 7 },
          { name: 'Layout & Composition', total: 6 },
          { name: 'Branding', total: 5 },
          { name: 'Print Design', total: 4 },
          { name: 'Social Media Design', total: 5 },
          { name: 'Infographics', total: 4 },
        ],
      },
      {
        id: 'motion-graphics',
        name: 'Motion Graphics',
        icon: '🎬',
        color: '#A29BFE',
        description: 'Animated visuals & motion design',
        topics: [
          { name: 'After Effects Basics', total: 8 },
          { name: 'Keyframing', total: 6 },
          { name: 'Expressions', total: 5 },
          { name: 'Character Animation', total: 6 },
          { name: 'Typography Animation', total: 5 },
          { name: '3D in AE', total: 5 },
          { name: 'Lottie Animations', total: 4 },
        ],
      },
      {
        id: '3d-modeling',
        name: '3D Modeling',
        icon: '🧊',
        color: '#00CEC9',
        description: '3D art, modeling & rendering',
        topics: [
          { name: 'Blender Basics', total: 8 },
          { name: 'Modeling', total: 7 },
          { name: 'Texturing', total: 6 },
          { name: 'Lighting', total: 5 },
          { name: 'Rendering', total: 5 },
          { name: 'Animation', total: 6 },
          { name: 'Sculpting', total: 5 },
        ],
      },
      {
        id: 'game-dev',
        name: 'Game Development',
        icon: '🎮',
        color: '#6C5CE7',
        description: 'Build games from concept to launch',
        topics: [
          { name: 'Game Design Principles', total: 6 },
          { name: 'Unity Basics', total: 8 },
          { name: 'Godot', total: 6 },
          { name: 'Game Physics', total: 5 },
          { name: 'Player Mechanics', total: 6 },
          { name: 'Level Design', total: 5 },
          { name: 'Audio', total: 4 },
          { name: 'Publishing', total: 4 },
        ],
      },
      {
        id: 'product-design',
        name: 'Product Design',
        icon: '📦',
        color: '#9B59B6',
        description: 'End-to-end digital product design',
        topics: [
          { name: 'User Research', total: 7 },
          { name: 'Personas & Journey Maps', total: 6 },
          { name: 'Information Architecture', total: 6 },
          { name: 'Wireframing', total: 7 },
          { name: 'Prototyping', total: 7 },
          { name: 'Visual Design', total: 6 },
          { name: 'Design Systems', total: 7 },
          { name: 'Usability Testing', total: 6 },
          { name: 'Handoff to Dev', total: 5 },
          { name: 'Design Ops', total: 4 },
        ],
      },
      {
        id: 'ux-design-roadmap',
        name: 'UX Design',
        icon: '🧑🎨',
        color: '#E74C3C',
        description: 'Design delightful user experiences',
        topics: [
          { name: 'UX Principles', total: 7 },
          { name: 'User Research', total: 7 },
          { name: 'Personas', total: 5 },
          { name: 'User Flows', total: 6 },
          { name: 'Wireframing', total: 6 },
          { name: 'Prototyping', total: 7 },
          { name: 'Usability Testing', total: 6 },
          { name: 'Accessibility', total: 6 },
          { name: 'Interaction Design', total: 6 },
          { name: 'UX Writing', total: 5 },
        ],
      },
      {
        id: 'design-systems',
        name: 'Design Systems',
        icon: '🧱',
        color: '#1ABC9C',
        description: 'Build & maintain scalable design systems',
        topics: [
          { name: 'Design Tokens', total: 6 },
          { name: 'Component Library', total: 8 },
          { name: 'Documentation', total: 6 },
          { name: 'Figma/Sketch', total: 5 },
          { name: 'Storybook', total: 6 },
          { name: 'Accessibility', total: 6 },
          { name: 'Versioning', total: 5 },
          { name: 'Governance', total: 4 },
          { name: 'Adoption Strategy', total: 4 },
          { name: 'Maintenance', total: 4 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 11. Business & Management
  // ─────────────────────────────────────────────
  {
    id: 'business',
    name: 'Business & Management',
    icon: '💼',
    roadmaps: [
      {
        id: 'product-management',
        name: 'Product Management',
        icon: '📋',
        color: '#E17055',
        description: 'Strategy, roadmaps & product thinking',
        topics: [
          { name: 'Product Strategy', total: 6 },
          { name: 'User Stories', total: 5 },
          { name: 'Roadmapping', total: 5 },
          { name: 'Prioritization Frameworks', total: 6 },
          { name: 'Metrics & KPIs', total: 5 },
          { name: 'A/B Testing', total: 4 },
          { name: 'Stakeholder Management', total: 5 },
          { name: 'Launch Planning', total: 4 },
        ],
      },
      {
        id: 'digital-marketing',
        name: 'Digital Marketing',
        icon: '📢',
        color: '#00B894',
        description: 'SEO, ads & growth marketing tactics',
        topics: [
          { name: 'SEO', total: 8 },
          { name: 'Content Marketing', total: 6 },
          { name: 'Social Media Marketing', total: 6 },
          { name: 'Email Marketing', total: 5 },
          { name: 'Google Ads', total: 6 },
          { name: 'Facebook Ads', total: 5 },
          { name: 'Analytics', total: 5 },
          { name: 'Conversion Optimization', total: 5 },
        ],
      },
      {
        id: 'business-analytics',
        name: 'Business Analytics',
        icon: '📊',
        color: '#6C5CE7',
        description: 'Data-driven business decision making',
        topics: [
          { name: 'Business Metrics', total: 6 },
          { name: 'Financial Analysis', total: 5 },
          { name: 'Market Analysis', total: 5 },
          { name: 'Competitive Analysis', total: 4 },
          { name: 'Forecasting', total: 5 },
          { name: 'Risk Analysis', total: 4 },
          { name: 'Strategy Frameworks', total: 6 },
        ],
      },
      {
        id: 'entrepreneurship',
        name: 'Entrepreneurship',
        icon: '🚀',
        color: '#FDCB6E',
        description: 'Build & grow your startup from zero',
        topics: [
          { name: 'Ideation', total: 5 },
          { name: 'Market Validation', total: 5 },
          { name: 'Business Models', total: 6 },
          { name: 'Funding & VC', total: 5 },
          { name: 'Legal & Compliance', total: 4 },
          { name: 'Team Building', total: 4 },
          { name: 'Growth Hacking', total: 5 },
          { name: 'Pitching', total: 4 },
        ],
      },
      {
        id: 'project-management',
        name: 'Project Management',
        icon: '📅',
        color: '#0984E3',
        description: 'Agile, Scrum & project delivery',
        topics: [
          { name: 'Agile Methodology', total: 8 },
          { name: 'Scrum Framework', total: 7 },
          { name: 'Kanban', total: 5 },
          { name: 'Sprint Planning', total: 5 },
          { name: 'Risk Management', total: 5 },
          { name: 'Stakeholder Communication', total: 4 },
          { name: 'Tools (Jira/Asana)', total: 5 },
          { name: 'PMP Concepts', total: 6 },
        ],
      },
      {
        id: 'devrel',
        name: 'Developer Relations',
        icon: '🤝',
        color: '#2ECC71',
        description: 'Build developer communities & advocacy',
        topics: [
          { name: 'Community Building', total: 7 },
          { name: 'Technical Writing', total: 6 },
          { name: 'Public Speaking', total: 6 },
          { name: 'Developer Experience', total: 7 },
          { name: 'Documentation', total: 6 },
          { name: 'API Evangelism', total: 5 },
          { name: 'Event Management', total: 5 },
          { name: 'Content Strategy', total: 5 },
          { name: 'Metrics & Analytics', total: 5 },
          { name: 'Open Source', total: 5 },
        ],
      },
      {
        id: 'tech-writing-roadmap',
        name: 'Technical Writing',
        icon: '✍️',
        color: '#3498DB',
        description: 'Write clear technical documentation',
        topics: [
          { name: 'Writing Fundamentals', total: 7 },
          { name: 'Documentation Types', total: 6 },
          { name: 'API Documentation', total: 7 },
          { name: 'Style Guides', total: 5 },
          { name: 'Markdown & Tools', total: 6 },
          { name: 'Information Architecture', total: 6 },
          { name: 'Diagrams & Visuals', total: 5 },
          { name: 'Review Process', total: 5 },
          { name: 'Docs as Code', total: 5 },
          { name: 'User Guides', total: 5 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 12. Finance & Blockchain
  // ─────────────────────────────────────────────
  {
    id: 'finance',
    name: 'Finance & Blockchain',
    icon: '💰',
    roadmaps: [
      {
        id: 'financial-markets',
        name: 'Financial Markets',
        icon: '📈',
        color: '#00B894',
        description: 'Stock markets, trading & investing',
        topics: [
          { name: 'Stock Market Basics', total: 8 },
          { name: 'Technical Analysis', total: 7 },
          { name: 'Fundamental Analysis', total: 6 },
          { name: 'Options & Derivatives', total: 7 },
          { name: 'Risk Management', total: 5 },
          { name: 'Portfolio Theory', total: 5 },
          { name: 'Mutual Funds', total: 5 },
          { name: 'Behavioral Finance', total: 4 },
        ],
      },
      {
        id: 'blockchain-web3',
        name: 'Blockchain & Web3',
        icon: '⛓️',
        color: '#6C5CE7',
        description: 'Decentralized apps & smart contracts',
        topics: [
          { name: 'Blockchain Fundamentals', total: 8 },
          { name: 'Ethereum', total: 6 },
          { name: 'Smart Contracts (Solidity)', total: 8 },
          { name: 'DeFi', total: 6 },
          { name: 'NFTs', total: 4 },
          { name: 'DAOs', total: 4 },
          { name: 'Web3 Development', total: 6 },
          { name: 'Security', total: 5 },
        ],
      },
      {
        id: 'personal-finance',
        name: 'Personal Finance',
        icon: '💵',
        color: '#E17055',
        description: 'Budgeting, investing & money skills',
        topics: [
          { name: 'Budgeting', total: 5 },
          { name: 'Saving & Investing', total: 6 },
          { name: 'Tax Planning', total: 5 },
          { name: 'Insurance', total: 4 },
          { name: 'Retirement Planning', total: 5 },
          { name: 'Debt Management', total: 4 },
          { name: 'Real Estate', total: 4 },
        ],
      },
      {
        id: 'fintech',
        name: 'FinTech',
        icon: '🏦',
        color: '#0984E3',
        description: 'Financial technology & innovation',
        topics: [
          { name: 'Payment Systems', total: 6 },
          { name: 'Digital Banking', total: 5 },
          { name: 'Lending Platforms', total: 4 },
          { name: 'RegTech', total: 4 },
          { name: 'InsurTech', total: 4 },
          { name: 'Robo-Advisors', total: 4 },
          { name: 'Open Banking', total: 4 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 13. Soft Skills & Career
  // ─────────────────────────────────────────────
  {
    id: 'career',
    name: 'Soft Skills & Career',
    icon: '🎯',
    roadmaps: [
      {
        id: 'technical-writing',
        name: 'Technical Writing',
        icon: '✍️',
        color: '#00CEC9',
        description: 'Write clear docs, blogs & API guides',
        topics: [
          { name: 'Documentation', total: 6 },
          { name: 'API Docs', total: 5 },
          { name: 'Blog Writing', total: 5 },
          { name: 'READMEs', total: 4 },
          { name: 'Style Guides', total: 4 },
          { name: 'Diagrams & Visuals', total: 4 },
          { name: 'Version Control for Docs', total: 3 },
        ],
      },
      {
        id: 'public-speaking',
        name: 'Public Speaking',
        icon: '🎤',
        color: '#E84393',
        description: 'Deliver impactful talks & speeches',
        topics: [
          { name: 'Overcoming Fear', total: 4 },
          { name: 'Structuring Talks', total: 5 },
          { name: 'Slide Design', total: 5 },
          { name: 'Storytelling', total: 5 },
          { name: 'Body Language', total: 4 },
          { name: 'Q&A Handling', total: 3 },
          { name: 'Virtual Presentations', total: 4 },
        ],
      },
      {
        id: 'interview-prep',
        name: 'Interview Preparation',
        icon: '🎯',
        color: '#6C5CE7',
        description: 'Ace coding & behavioral interviews',
        topics: [
          { name: 'Resume Building', total: 5 },
          { name: 'Coding Interviews', total: 12 },
          { name: 'System Design Interviews', total: 8 },
          { name: 'Behavioral Questions', total: 6 },
          { name: 'HR Rounds', total: 4 },
          { name: 'Salary Negotiation', total: 4 },
          { name: 'Mock Interviews', total: 5 },
        ],
      },
      {
        id: 'communication',
        name: 'Communication Skills',
        icon: '💬',
        color: '#FDCB6E',
        description: 'Effective workplace communication',
        topics: [
          { name: 'Active Listening', total: 4 },
          { name: 'Email Writing', total: 5 },
          { name: 'Meeting Management', total: 4 },
          { name: 'Feedback Skills', total: 4 },
          { name: 'Cross-Cultural Communication', total: 4 },
          { name: 'Conflict Resolution', total: 4 },
          { name: 'Presentation Skills', total: 5 },
        ],
      },
      {
        id: 'leadership',
        name: 'Leadership',
        icon: '👑',
        color: '#E17055',
        description: 'Lead teams & drive organizational change',
        topics: [
          { name: 'Team Management', total: 6 },
          { name: 'Decision Making', total: 5 },
          { name: 'Delegation', total: 4 },
          { name: 'Mentoring', total: 5 },
          { name: 'Strategic Thinking', total: 5 },
          { name: 'Emotional Intelligence', total: 5 },
          { name: 'Change Management', total: 4 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 14. Exam Preparation
  // ─────────────────────────────────────────────
  {
    id: 'exams',
    name: 'Exam Preparation',
    icon: '📝',
    roadmaps: [
      {
        id: 'jee',
        name: 'JEE (Mains + Advanced)',
        icon: '🎓',
        color: '#E84393',
        description: 'Complete JEE prep across PCM',
        topics: [
          { name: 'Mathematics - Algebra', total: 20 },
          { name: 'Mathematics - Calculus', total: 18 },
          { name: 'Mathematics - Coordinate Geometry', total: 15 },
          { name: 'Mathematics - Trigonometry', total: 10 },
          { name: 'Physics - Mechanics', total: 22 },
          { name: 'Physics - Electrodynamics', total: 18 },
          { name: 'Physics - Optics', total: 10 },
          { name: 'Physics - Modern Physics', total: 12 },
          { name: 'Chemistry - Physical', total: 15 },
          { name: 'Chemistry - Organic', total: 20 },
          { name: 'Chemistry - Inorganic', total: 15 },
        ],
      },
      {
        id: 'neet',
        name: 'NEET',
        icon: '🩺',
        color: '#00B894',
        description: 'Medical entrance exam preparation',
        topics: [
          { name: 'Physics', total: 35 },
          { name: 'Chemistry - Physical', total: 12 },
          { name: 'Chemistry - Organic', total: 15 },
          { name: 'Chemistry - Inorganic', total: 12 },
          { name: 'Biology - Zoology', total: 25 },
          { name: 'Biology - Botany', total: 25 },
          { name: 'Biology - Genetics & Evolution', total: 15 },
          { name: 'Biology - Ecology', total: 10 },
        ],
      },
      {
        id: 'gate-cse',
        name: 'GATE CSE',
        icon: '🖥️',
        color: '#6C5CE7',
        description: 'GATE CS & IT exam preparation',
        topics: [
          { name: 'DSA', total: 20 },
          { name: 'Operating Systems', total: 15 },
          { name: 'DBMS', total: 12 },
          { name: 'Computer Networks', total: 12 },
          { name: 'TOC', total: 10 },
          { name: 'Discrete Math', total: 10 },
          { name: 'Compiler Design', total: 8 },
          { name: 'Digital Logic', total: 8 },
          { name: 'COA', total: 8 },
          { name: 'Engineering Math', total: 10 },
          { name: 'Aptitude', total: 6 },
        ],
      },
      {
        id: 'upsc',
        name: 'UPSC CSE',
        icon: '🏛️',
        color: '#0984E3',
        description: 'Civil services exam preparation',
        topics: [
          { name: 'Indian Polity', total: 20 },
          { name: 'Indian History', total: 18 },
          { name: 'Geography', total: 15 },
          { name: 'Indian Economy', total: 15 },
          { name: 'Science & Tech', total: 12 },
          { name: 'Environment', total: 10 },
          { name: 'Ethics', total: 12 },
          { name: 'Current Affairs', total: 25 },
          { name: 'Essay Writing', total: 8 },
        ],
      },
      {
        id: 'cat',
        name: 'CAT',
        icon: '📚',
        color: '#FDCB6E',
        description: 'MBA entrance exam preparation',
        topics: [
          { name: 'Quantitative Aptitude - Arithmetic', total: 15 },
          { name: 'QA - Algebra', total: 12 },
          { name: 'QA - Geometry', total: 10 },
          { name: 'QA - Number System', total: 8 },
          { name: 'DILR - Data Interpretation', total: 12 },
          { name: 'DILR - Logical Reasoning', total: 12 },
          { name: 'VARC - Reading Comprehension', total: 15 },
          { name: 'VARC - Verbal Ability', total: 10 },
        ],
      },
      {
        id: 'ssc-cgl',
        name: 'SSC CGL',
        icon: '📝',
        color: '#E17055',
        description: 'SSC Combined Graduate Level exam',
        topics: [
          { name: 'General Intelligence', total: 15 },
          { name: 'English Language', total: 15 },
          { name: 'Quantitative Aptitude', total: 18 },
          { name: 'General Awareness', total: 15 },
        ],
      },
    ],
  },

  // ─────────────────────────────────────────────
  // 15. Best Practices
  // ─────────────────────────────────────────────
  {
    id: 'best-practices',
    name: 'Best Practices',
    icon: '✅',
    roadmaps: [
      {
        id: 'aws-best-practices',
        name: 'AWS Best Practices',
        icon: '☁️',
        color: '#FF9900',
        description: 'AWS architecture & operational best practices',
        topics: [
          { name: 'Well-Architected Framework', total: 8 },
          { name: 'Security Best Practices', total: 7 },
          { name: 'Cost Optimization', total: 7 },
          { name: 'Performance Efficiency', total: 6 },
          { name: 'Operational Excellence', total: 6 },
          { name: 'Reliability', total: 6 },
          { name: 'Networking', total: 6 },
          { name: 'IAM Policies', total: 6 },
          { name: 'Monitoring & Logging', total: 5 },
          { name: 'Disaster Recovery', total: 5 },
        ],
      },
      {
        id: 'api-security-bp',
        name: 'API Security Best Practices',
        icon: '🔒',
        color: '#E74C3C',
        description: 'Secure your APIs against common threats',
        topics: [
          { name: 'Authentication & Authorization', total: 8 },
          { name: 'Input Validation', total: 7 },
          { name: 'Rate Limiting', total: 6 },
          { name: 'OWASP Top 10', total: 7 },
          { name: 'Encryption', total: 6 },
          { name: 'CORS & CSP', total: 5 },
          { name: 'API Keys & Tokens', total: 6 },
          { name: 'Logging & Monitoring', total: 5 },
          { name: 'Error Handling', total: 5 },
          { name: 'Security Testing', total: 5 },
        ],
      },
      {
        id: 'backend-perf-bp',
        name: 'Backend Performance',
        icon: '⚡',
        color: '#F39C12',
        description: 'Optimize backend speed & scalability',
        topics: [
          { name: 'Database Optimization', total: 8 },
          { name: 'Caching Strategies', total: 7 },
          { name: 'Connection Pooling', total: 5 },
          { name: 'Async Processing', total: 7 },
          { name: 'Load Balancing', total: 6 },
          { name: 'Profiling & Benchmarking', total: 6 },
          { name: 'Memory Management', total: 5 },
          { name: 'Query Optimization', total: 7 },
          { name: 'CDN Integration', total: 4 },
          { name: 'Auto-Scaling', total: 5 },
        ],
      },
      {
        id: 'frontend-perf-bp',
        name: 'Frontend Performance',
        icon: '🚀',
        color: '#3498DB',
        description: 'Optimize frontend loading & rendering',
        topics: [
          { name: 'Core Web Vitals', total: 8 },
          { name: 'Bundle Optimization', total: 7 },
          { name: 'Lazy Loading', total: 6 },
          { name: 'Image Optimization', total: 6 },
          { name: 'Code Splitting', total: 6 },
          { name: 'Caching Strategies', total: 5 },
          { name: 'Critical CSS', total: 5 },
          { name: 'Service Workers', total: 5 },
          { name: 'Rendering Patterns', total: 6 },
          { name: 'Performance Auditing', total: 5 },
        ],
      },
      {
        id: 'code-review-bp',
        name: 'Code Review Best Practices',
        icon: '👀',
        color: '#2ECC71',
        description: 'Conduct effective and kind code reviews',
        topics: [
          { name: 'Review Checklist', total: 7 },
          { name: 'Architecture Review', total: 6 },
          { name: 'Security Review', total: 6 },
          { name: 'Performance Review', total: 5 },
          { name: 'Testing Coverage', total: 5 },
          { name: 'Readability & Naming', total: 5 },
          { name: 'Documentation Review', total: 4 },
          { name: 'Automated Checks', total: 5 },
          { name: 'Review Etiquette', total: 5 },
          { name: 'Approval Workflows', total: 4 },
        ],
      },
    ],
  },
];
