/**
 * ANALYXX WhatsApp Bot — PYQ Handler
 *
 * Looks up papers in Supabase `library_papers` table (the updated database)
 * and sends the actual PDF document directly via WhatsApp.
 *
 * For RTU papers, the handler first checks for Analyxx-branded versions
 * (cover page + original) stored at:
 *   rtu-csit/Sem {n}/{Subject} {year}.pdf
 *   rtu-me/Sem {n}/{Subject} {year}.pdf
 *   rtu-ce/Sem {n}/{Subject} {year}.pdf
 *   rtu-eeec/Sem {n}/{Subject} {year}.pdf
 *   rtu-1styear/Sem {n}/{Subject} {year}.pdf
 *
 * If no branded version exists, falls back to the raw PDF at the DB storage_path.
 *
 * For CBSE/NEET/JEE papers, the DB storage_path already points to branded PDFs
 * generated by generate_template_papers.py.
 *
 * Storage bucket: library-papers (public)
 * Public URL pattern: {SUPABASE_URL}/storage/v1/object/public/library-papers/{storage_path}
 */

const { createClient } = require("@supabase/supabase-js");
const axios = require("axios");
const fs = require("fs");
const path = require("path");
const config = require("../config");
const wa = require("../whatsapp");
const logger = require("../logger");
const sessionStore = require("../sessionStore");
const { getRtuSubjects } = require("../examData");

const supabase = createClient(config.SUPABASE_URL, config.SUPABASE_SERVICE_KEY);

/**
 * Number of years (including current) a free user can access.
 * E.g. FREE_YEAR_WINDOW = 3 means current year, current-1, current-2.
 */
const FREE_YEAR_WINDOW = 3;

/**
 * Check whether a WhatsApp phone number belongs to a Pro subscriber.
 *
 * Lookup chain:
 *   1. whatsapp_users  → get user_id by phone
 *   2. subscriptions   → check for an active pro_* plan
 *
 * Returns true if the user has an active Pro subscription, false otherwise.
 */
async function checkIsProUser(phone) {
  try {
    // Step 1: Find the ANALYXX user_id linked to this phone
    const { data: waUser, error: waErr } = await supabase
      .from("whatsapp_users")
      .select("user_id")
      .eq("phone", phone)
      .single();

    if (waErr || !waUser) {
      logger.debug(`No whatsapp_users entry for ${phone}`);
      return false;
    }

    // Step 2: Check if that user has an active Pro subscription
    const { data: sub, error: subErr } = await supabase
      .from("subscriptions")
      .select("plan, status, expires_at")
      .eq("user_id", waUser.user_id)
      .single();

    if (subErr || !sub) {
      logger.debug(`No subscription found for user_id ${waUser.user_id}`);
      return false;
    }

    // Must be an active pro_* plan
    if (!sub.plan.startsWith("pro_") || sub.status !== "active") {
      return false;
    }

    // Check expiry (null expires_at means lifetime / no expiry)
    if (sub.expires_at && new Date(sub.expires_at) < new Date()) {
      return false;
    }

    return true;
  } catch (err) {
    logger.error("checkIsProUser error", { error: err.message, phone });
    return false;
  }
}

/**
 * Send the subscription-required message to the user.
 */
async function sendSubscriptionRequiredMessage(to) {
  const pricingUrl = `${config.FRONTEND_URL.replace(/\/$/, "")}/billing`;
  await wa.sendText(
    to,
    `🔒 *Pro Subscription Required*\n\nYou need a Pro subscription to access papers older than the last ${FREE_YEAR_WINDOW} years.\n\nUpgrade now to unlock the full paper archive:\n🔗 ${pricingUrl}`
  );
  await wa.sendButtons(
    to,
    "Upgrade to ANALYXX Pro for unlimited access to all years!",
    [
      { id: "action_menu", title: "Browse Free Papers" },
    ]
  );
}

/**
 * Build a public download URL for a paper in the library-papers bucket.
 */
function buildPdfUrl(storagePath) {
  return `${config.BACKEND_URL.replace(/\/$/, "")}/api/v1/library/clean-pdf?path=${encodeURIComponent(storagePath)}`;
}

function getFilesFromLocalManifest(folder) {
  try {
    const manifestPath = path.join(__dirname, "../r2_paper_manifest.json");
    if (fs.existsSync(manifestPath)) {
      const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
      const files = manifest[folder] || [];
      return files.map((name) => ({ name }));
    }
  } catch (err) {
    logger.debug("Failed to read local manifest fallback in pyqHandler", { error: err.message });
  }
  return null;
}

/**
 * Map DB branch IDs to the old branded storage prefix used by generate_rtu_papers.py.
 *   cs, it       → rtu-csit
 *   mechanical   → rtu-me
 *   civil        → rtu-ce
 *   electrical, electronics → rtu-eeec
 *   1st-year     → rtu-1styear
 */
const BRANCH_TO_BRANDED_PREFIX = {
  cs: "rtu-csit",
  it: "rtu-csit",
  mechanical: "rtu-me",
  civil: "rtu-ce",
  electrical: "rtu-eeec",
  electronics: "rtu-eeec",
  ece: "rtu-eeec",
  "1st-year": "rtu-1styear",
};

/**
 * Try to find an Analyxx-branded version of an RTU paper.
 * Branded papers are stored at: {prefix}/Sem {n}/{SubjectName} {year}.pdf
 *
 * Strategy: list files in the semester folder and fuzzy-match by subject + year.
 * Returns the storage path of the branded file if found, null otherwise.
 */
async function findBrandedRtuPaper(branch, semester, subjectName, year) {
  try {
    const prefix = BRANCH_TO_BRANDED_PREFIX[branch?.toLowerCase()];
    if (!prefix || !semester || !year) return null;

    const folderPath = `${prefix}/Sem ${semester}`;
    let files;
    try {
      const response = await axios.get(`${config.BACKEND_URL}/api/v1/library/list-papers`, {
        params: { folder: folderPath }
      });
      files = response.data;
    } catch (storageErr) {
      logger.debug("Storage listing fallback failed in findBrandedRtuPaper, trying local manifest", { folder: folderPath, error: storageErr.message });
      files = getFilesFromLocalManifest(folderPath);
    }

    if (!files || files.length === 0) return null;

    // Normalize subject for comparison
    const normalizedSubject = subjectName.toLowerCase().replace(/[-_&]/g, " ").replace(/\s+/g, " ").trim();

    // Try exact match first: "{SubjectName} {year}.pdf"
    const exactName = `${subjectName} ${year}.pdf`;
    const exact = files.find((f) => f.name === exactName);
    if (exact) {
      const path = `${folderPath}/${exact.name}`;
      logger.info(`Found branded RTU paper (exact): ${path}`);
      return path;
    }

    // Fuzzy match: find files ending with "{year}.pdf" that contain the subject name
    const candidates = files.filter((f) => f.name.endsWith(`${year}.pdf`));
    for (const candidate of candidates) {
      const candidateName = candidate.name
        .replace(`.pdf`, "")
        .replace(` ${year}`, "")
        .toLowerCase()
        .replace(/[-_&]/g, " ")
        .replace(/\s+/g, " ")
        .trim();

      // Check if subject names are similar enough (one contains the other, or starts the same)
      if (
        candidateName.includes(normalizedSubject) ||
        normalizedSubject.includes(candidateName) ||
        candidateName.split(" ").slice(0, 2).join(" ") === normalizedSubject.split(" ").slice(0, 2).join(" ")
      ) {
        const path = `${folderPath}/${candidate.name}`;
        logger.info(`Found branded RTU paper (fuzzy): ${path}`);
        return path;
      }
    }

    return null;
  } catch (err) {
    logger.debug(`Branded RTU lookup failed: ${err.message}`);
    return null;
  }
}

/**
 * Fetch and send a regular (non-RTU) PYQ paper to the user as a PDF document.
 * Queries the library_papers database table to ensure we use the updated database.
 * Returns true if paper was found, false otherwise.
 */
async function handlePyqRequest(to, examId, examName, subject, year) {
  if (!year) {
    await wa.sendText(to, `Please specify the year.\n\nExample: "${examName} ${subject || ""} 2024"`);
    return false;
  }

  // ── Subscription gate: free users limited to last 3 years ──
  const requestedYear = parseInt(year, 10);
  const cutoffYear = new Date().getFullYear() - (FREE_YEAR_WINDOW - 1);
  if (requestedYear < cutoffYear) {
    const isPro = await checkIsProUser(to);
    if (!isPro) {
      logger.info(`Blocked non-pro user ${to} from accessing ${examId} ${subject} ${year} (cutoff: ${cutoffYear})`);
      await sendSubscriptionRequiredMessage(to);
      return false;
    }
  }

  logger.info(`Looking up paper in database: exam=${examId}, subject=${subject}, year=${year}`);

  try {
    // Query the library_papers database table for the paper
    let query = supabase
      .from("library_papers")
      .select("storage_path, subject, year, exam")
      .eq("year", year);

    // Match exam (case-insensitive comparison via ilike)
    query = query.ilike("exam", examId);

    if (subject) {
      query = query.ilike("subject", subject);
    }

    const { data: papers, error } = await query.limit(1);

    if (error) {
      logger.error("Supabase database error", { error });
      await wa.sendText(to, "Sorry, I had trouble accessing the paper library. Please try again later.");
      return false;
    }

    const paperLabel = subject ? `${examName} ${subject} ${year}` : `${examName} ${year}`;

    if (!papers || papers.length === 0) {
      // Paper not found in our database — try a broader search
      const { data: broadSearch } = await supabase
        .from("library_papers")
        .select("storage_path, subject, year, exam")
        .eq("year", year)
        .ilike("exam", `%${examId.replace(/-/g, "%")}%`)
        .ilike("subject", subject ? `%${subject}%` : "%")
        .limit(1);

      if (broadSearch && broadSearch.length > 0) {
        const broadFileName = paper.storage_path ? path.basename(paper.storage_path) : "";
        let viewUrl = `${config.FRONTEND_URL.replace(/\/$/, "")}/library/view?exam=${examId}&subject=${encodeURIComponent(paper.subject || subject || "Paper")}&year=${year}`;
        if (broadFileName) viewUrl += `&file=${encodeURIComponent(broadFileName)}`;

        logger.info(`Sending paper link (broad match): ${viewUrl}`);
        await wa.sendText(
          to,
          `📄 *${examName} — ${paper.subject || "Paper"} (${year})*\n\nClick the link below to view the paper on the ANALYXX website:\n🔗 ${viewUrl}`
        );

        sessionStore.set(to, {
          step: "paper_sent",
          examId,
          examName,
          subject: paper.subject || subject,
          year,
        });

        await wa.sendButtons(
          to,
          "📎 Paper sent! What would you like to do next?",
          [
            { id: `action_analyze_${examId}`, title: "AI Analysis" },
            { id: `action_topics_${examId}`, title: "Key Topics" },
            { id: "action_menu", title: "Browse More" },
          ]
        );

        return true;
      }

      // Storage fallback — list files directly from Supabase Storage
      // Handles exams like JEE Mains/Advanced whose papers aren't indexed in the DB yet
      const storageFolder = `${examId}/${subject || "Paper"}`;
      let files;
      try {
        const response = await axios.get(`${config.BACKEND_URL}/api/v1/library/list-papers`, {
          params: { folder: storageFolder }
        });
        files = response.data;
      } catch (storageErr) {
        logger.debug("Storage fallback failed, trying local manifest", { error: storageErr.message });
        files = getFilesFromLocalManifest(storageFolder);
      }

      if (files && files.length > 0) {
        // Find the first file matching the requested year
        const matchingFile = files.find((f) => f.name.startsWith(`${year}`));
        if (matchingFile) {
          const storagePath = `${storageFolder}/${matchingFile.name}`;
          const viewUrl = `${config.FRONTEND_URL.replace(/\/$/, "")}/library/view?exam=${examId}&subject=${encodeURIComponent(subject || "Paper")}&year=${year}&file=${encodeURIComponent(matchingFile.name)}`;

          logger.info(`Sending paper link (storage fallback): ${viewUrl}`);
          await wa.sendText(
            to,
            `📄 *${examName} — ${subject || "Paper"} (${year})*\n\nClick the link below to view the paper on the ANALYXX website:\n🔗 ${viewUrl}`
          );

          sessionStore.set(to, {
            step: "paper_sent",
            examId,
            examName,
            subject: subject || "Paper",
            year,
          });

          await wa.sendButtons(
            to,
            "📎 Paper sent! What would you like to do next?",
            [
              { id: `action_analyze_${examId}`, title: "AI Analysis" },
              { id: `action_topics_${examId}`, title: "Key Topics" },
              { id: "action_menu", title: "Browse More" },
            ]
          );

          return true;
        }
      }

      // Truly not found
      await wa.sendButtons(
        to,
        `Sorry, *${paperLabel}* paper is not available in our library yet.\n\nWould you like to:`,
        [
          { id: "action_menu", title: "Browse Other Papers" },
          { id: `action_analyze_nopaper`, title: "AI Analysis Instead" },
        ],
        null,
        "Paper not found"
      );
      return false;
    }

    // Paper found — send the paper link
    const paper = papers[0];
    const dbFileName = paper.storage_path ? path.basename(paper.storage_path) : "";
    let viewUrl = `${config.FRONTEND_URL.replace(/\/$/, "")}/library/view?exam=${examId}&subject=${encodeURIComponent(paper.subject || subject || "Paper")}&year=${year}`;
    if (dbFileName) viewUrl += `&file=${encodeURIComponent(dbFileName)}`;

    logger.info(`Sending paper link: ${viewUrl}`);
    await wa.sendText(
      to,
      `📄 *${examName} — ${paper.subject || "Paper"} (${year})*\n\nClick the link below to view the paper on the ANALYXX website:\n🔗 ${viewUrl}`
    );

    // Save session so follow-up action buttons have context
    sessionStore.set(to, {
      step: "paper_sent",
      examId,
      examName,
      subject: paper.subject || subject,
      year,
    });

    // Follow up with action buttons
    await wa.sendButtons(
      to,
      "📎 Paper sent! What would you like to do next?",
      [
        { id: `action_analyze_${examId}`, title: "AI Analysis" },
        { id: `action_topics_${examId}`, title: "Key Topics" },
        { id: "action_menu", title: "Browse More" },
      ]
    );

    return true;
  } catch (err) {
    logger.error("PYQ handler error", { error: err.message, examId, subject, year });
    await wa.sendText(to, "Something went wrong while retrieving the paper. Please try again.");
    return false;
  }
}

/**
 * Fetch and send an RTU PYQ paper to the user as a PDF document.
 * Queries the library_papers database table, then checks for branded version.
 *
 * Priority order:
 *   1. Branded PDF (Analyxx cover page prepended) at rtu-{branch}/Sem {n}/{Subject} {year}.pdf
 *   2. Raw PDF from DB storage_path
 */
async function handleRtuPyqRequest(to, branchId, branchYearId, subjectId, subjectName, calendarYear) {
  if (!subjectId || !calendarYear) {
    await wa.sendText(to, "Please select a subject and year first. Type *menu* to start over.");
    return false;
  }

  // ── Subscription gate: free users limited to last 3 years ──
  const requestedCalYear = parseInt(calendarYear, 10);
  const cutoffYear = new Date().getFullYear() - (FREE_YEAR_WINDOW - 1);
  if (requestedCalYear < cutoffYear) {
    const isPro = await checkIsProUser(to);
    if (!isPro) {
      logger.info(`Blocked non-pro user ${to} from accessing RTU ${branchId} ${subjectName} ${calendarYear} (cutoff: ${cutoffYear})`);
      await sendSubscriptionRequiredMessage(to);
      return false;
    }
  }

  logger.info(`Looking up RTU paper in database: branch=${branchId}, year=${branchYearId}, subject=${subjectName}, calYear=${calendarYear}`);

  try {
    // Determine semester number for the query
    let semNum = null;
    if (branchYearId !== "1st-year") {
      const subjectGroups = getRtuSubjects(branchId, branchYearId);
      const semGroup = subjectGroups.find((g) => g.subjects.some((s) => s.id === subjectId));
      semNum = semGroup ? parseInt(semGroup.semester.replace("Semester ", "")) : null;

      if (!semNum) {
        await wa.sendText(to, "Sorry, I couldn't determine the semester for that subject. Please try again.");
        return false;
      }
    }

    // Query the library_papers database table
    let query = supabase
      .from("library_papers")
      .select("storage_path, subject, year, exam, branch, semester")
      .ilike("exam", "rtu%")
      .eq("year", calendarYear)
      .ilike("subject", subjectName);

    if (branchId && branchYearId !== "1st-year") {
      query = query.ilike("branch", branchId);
    }
    if (semNum) {
      query = query.eq("semester", semNum);
    }

    const { data: papers, error } = await query.limit(1);

    if (error) {
      logger.error("Supabase database error (RTU)", { error });
      await wa.sendText(to, "Sorry, I had trouble accessing the paper library. Please try again later.");
      return false;
    }

    if (!papers || papers.length === 0) {
      // Try a broader search with fuzzy subject matching
      const { data: broadSearch } = await supabase
        .from("library_papers")
        .select("storage_path, subject, year, exam, branch, semester")
        .ilike("exam", "rtu%")
        .eq("year", calendarYear)
        .ilike("subject", `%${subjectName.split(" ")[0]}%`)
        .limit(1);

      if (broadSearch && broadSearch.length > 0) {
        const paper = broadSearch[0];

        // Determine semNum for the URL
        const subjectGroups = getRtuSubjects(paper.branch || branchId, branchYearId);
        const semGroup = subjectGroups.find((g) => g.subjects.some((s) => s.id === subjectId || s.name === (paper.subject || subjectName)));
        const finalSemNum = semGroup ? parseInt(semGroup.semester.replace("Semester ", "")) : semNum;

        let viewUrl = `${config.FRONTEND_URL.replace(/\/$/, "")}/library/view?exam=rtu&branchYear=${branchYearId}&subject=${encodeURIComponent(paper.subject || subjectName)}&year=${calendarYear}`;
        if (paper.branch || branchId) viewUrl += `&branch=${paper.branch || branchId}`;
        if (finalSemNum) viewUrl += `&sem=${finalSemNum}`;
        if (paper.storage_path) viewUrl += `&file=${encodeURIComponent(path.basename(paper.storage_path))}`;

        logger.info(`Sending RTU paper link (broad match): ${viewUrl}`);
        await wa.sendText(
          to,
          `📄 *RTU — ${paper.subject || subjectName} (${calendarYear})*\n\nClick the link below to view the paper on the ANALYXX website:\n🔗 ${viewUrl}`
        );

        sessionStore.set(to, {
          step: "rtu_paper_sent",
          examId: "rtu",
          examName: "RTU",
          branchId,
          branchYearId,
          subjectId,
          subjectName: paper.subject || subjectName,
          year: calendarYear,
        });

        await wa.sendButtons(
          to,
          "📎 Paper sent! What would you like to do next?",
          [
            { id: "rtu_back_subjects", title: "More Subjects" },
            { id: "rtu_back_years", title: "Different Year" },
            { id: "action_menu", title: "Main Menu" },
          ]
        );

        return true;
      }

      // Storage fallback — try to find the paper directly in the storage bucket
      // RTU papers may be uploaded to storage without DB entries
      const storagePaths = [];

      if (branchYearId === "1st-year") {
        // 1st year: rtu-1st-year/{Subject Name}/{year}.pdf
        storagePaths.push(`rtu-1st-year/${subjectName}/${calendarYear}.pdf`);
        // Also check branded path: rtu-1styear/Sem {n}/{Subject} {year}.pdf
        const sem = semNum || 1;
        storagePaths.push(`rtu-1styear/Sem ${sem}/${subjectName} ${calendarYear}.pdf`);
      } else if (branchId && semNum) {
        // Other years: rtu/{branch}/sem-{n}/{Subject Name}/{year}.pdf
        storagePaths.push(`rtu/${branchId}/sem-${semNum}/${subjectName}/${calendarYear}.pdf`);
        // Also check branded path
        const prefix = BRANCH_TO_BRANDED_PREFIX[branchId];
        if (prefix) {
          storagePaths.push(`${prefix}/Sem ${semNum}/${subjectName} ${calendarYear}.pdf`);
        }
      }

      for (const storagePath of storagePaths) {
        try {
          // Check if the file exists by trying to get its URL and verifying via list
          const folder = storagePath.substring(0, storagePath.lastIndexOf("/"));
          const fileName = storagePath.substring(storagePath.lastIndexOf("/") + 1);
          let files;
          try {
            const response = await axios.get(`${config.BACKEND_URL}/api/v1/library/list-papers`, {
              params: { folder }
            });
            files = response.data;
          } catch (storageErr) {
            logger.debug(`Storage listing failed in handleRtuPyqRequest for ${folder}, trying local manifest`, { error: storageErr.message });
            files = getFilesFromLocalManifest(folder);
          }

          if (files && files.some((f) => f.name === fileName)) {
            // Determine semNum for the URL
            const subjectGroups = getRtuSubjects(branchId, branchYearId);
            const semGroup = subjectGroups.find((g) => g.subjects.some((s) => s.id === subjectId || s.name === subjectName));
            const finalSemNum = semGroup ? parseInt(semGroup.semester.replace("Semester ", "")) : semNum;

            let viewUrl = `${config.FRONTEND_URL.replace(/\/$/, "")}/library/view?exam=rtu&branchYear=${branchYearId}&subject=${encodeURIComponent(subjectName)}&year=${calendarYear}&file=${encodeURIComponent(fileName)}`;
            if (branchId) viewUrl += `&branch=${branchId}`;
            if (finalSemNum) viewUrl += `&sem=${finalSemNum}`;

            logger.info(`Sending RTU paper link (storage fallback): ${viewUrl}`);
            await wa.sendText(
              to,
              `📄 *RTU — ${subjectName} (${calendarYear})*\n\nClick the link below to view the paper on the ANALYXX website:\n🔗 ${viewUrl}`
            );

            sessionStore.set(to, {
              step: "rtu_paper_sent",
              examId: "rtu",
              examName: "RTU",
              branchId,
              branchYearId,
              subjectId,
              subjectName,
              year: calendarYear,
            });

            await wa.sendButtons(
              to,
              "📎 Paper sent! What would you like to do next?",
              [
                { id: "rtu_back_subjects", title: "More Subjects" },
                { id: "rtu_back_years", title: "Different Year" },
                { id: "action_menu", title: "Main Menu" },
              ]
            );

            return true;
          }
        } catch (storageErr) {
          logger.debug(`Storage fallback check failed for ${storagePath}: ${storageErr.message}`);
        }
      }

      // Truly not found
      const branchName = branchId.toUpperCase();
      await wa.sendButtons(
        to,
        `Sorry, *RTU ${branchName} — ${subjectName} (${calendarYear})* paper is not available yet.\n\nWould you like to:`,
        [
          { id: "action_menu", title: "Browse Other Papers" },
          { id: "rtu_back_subjects", title: "Try Another Subject" },
        ],
        null,
        "Paper not found"
      );
      return false;
    }

    // Paper found in DB — send the paper link
    const paper = papers[0];

    // Determine semNum for the URL
    const subjectGroups = getRtuSubjects(paper.branch || branchId, branchYearId);
    const semGroup = subjectGroups.find((g) => g.subjects.some((s) => s.id === subjectId || s.name === (paper.subject || subjectName)));
    const finalSemNum = semGroup ? parseInt(semGroup.semester.replace("Semester ", "")) : semNum;

    let viewUrl = `${config.FRONTEND_URL.replace(/\/$/, "")}/library/view?exam=rtu&branchYear=${branchYearId}&subject=${encodeURIComponent(paper.subject || subjectName)}&year=${calendarYear}`;
    if (paper.branch || branchId) viewUrl += `&branch=${paper.branch || branchId}`;
    if (finalSemNum) viewUrl += `&sem=${finalSemNum}`;
    if (paper.storage_path) viewUrl += `&file=${encodeURIComponent(path.basename(paper.storage_path))}`;

    logger.info(`Sending RTU paper link: ${viewUrl}`);
    await wa.sendText(
      to,
      `📄 *RTU — ${paper.subject || subjectName} (${calendarYear})*\n\nClick the link below to view the paper on the ANALYXX website:\n🔗 ${viewUrl}`
    );

    // Save session context
    sessionStore.set(to, {
      step: "rtu_paper_sent",
      examId: "rtu",
      examName: "RTU",
      branchId,
      branchYearId,
      subjectId,
      subjectName: paper.subject || subjectName,
      year: calendarYear,
    });

    // Follow up with action buttons
    await wa.sendButtons(
      to,
      "📎 Paper sent! What would you like to do next?",
      [
        { id: "rtu_back_subjects", title: "More Subjects" },
        { id: "rtu_back_years", title: "Different Year" },
        { id: "action_menu", title: "Main Menu" },
      ]
    );

    return true;
  } catch (err) {
    logger.error("RTU PYQ handler error", { error: err.message, branchId, subjectName, calendarYear });
    await wa.sendText(to, "Something went wrong while retrieving the paper. Please try again.");
    return false;
  }
}

module.exports = { handlePyqRequest, handleRtuPyqRequest };
