#!/usr/bin/env python3
"""
Upload scraped RTU papers to Cloudflare R2.
Generated by check_and_scrape_rtu.py

Usage:
  python upload_scraped_to_r2.py                    # Upload all from manifest
  python upload_scraped_to_r2.py --dry-run           # Preview only
"""
import os, json, sys, time
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), "backend", ".env"))

MANIFEST_PATH = "/Users/ayush/Desktop/pyq-analyzer/papers_to_upload/RTU_SCRAPED/upload_manifest.json"

def upload_via_boto3(local_path, storage_path):
    """Upload via boto3 to R2."""
    import boto3
    from botocore.config import Config

    r2 = boto3.client(
        "s3",
        endpoint_url=os.getenv("R2_ENDPOINT_URL"),
        aws_access_key_id=os.getenv("R2_ACCESS_KEY_ID"),
        aws_secret_access_key=os.getenv("R2_SECRET_ACCESS_KEY"),
        config=Config(signature_version="s3v4"),
        region_name="auto",
    )
    bucket = os.getenv("R2_BUCKET_NAME", "analyxx-papers")
    r2_key = f"library-papers/{storage_path}"

    with open(local_path, "rb") as f:
        r2.put_object(Bucket=bucket, Key=r2_key, Body=f.read(), ContentType="application/pdf")
    return True

def main():
    dry_run = "--dry-run" in sys.argv

    with open(MANIFEST_PATH) as f:
        manifest = json.load(f)

    papers = manifest["papers"]
    print(f"\n📦 Upload Manifest: {len(papers)} papers")
    print(f"   Generated: {manifest['timestamp']}")

    if dry_run:
        print("\n[DRY RUN]")
        for p in papers:
            print(f"  → {p['storage_path']}")
        return

    uploaded = 0
    failed = 0
    for i, p in enumerate(papers, 1):
        local_path = p["local_path"]
        storage_path = p["storage_path"]

        if not os.path.exists(local_path):
            print(f"  [{i}/{len(papers)}] ❌ File not found: {local_path}")
            failed += 1
            continue

        print(f"  [{i}/{len(papers)}] 📤 {storage_path}...", end=" ")
        try:
            upload_via_boto3(local_path, storage_path)
            print("✅")
            uploaded += 1
        except Exception as e:
            print(f"❌ {str(e)[:60]}")
            failed += 1
        time.sleep(0.3)

    print(f"\n🎉 Done! ✅ {uploaded} uploaded | ❌ {failed} failed")

if __name__ == "__main__":
    main()
